//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DDFEntities1 : DbContext
    {
        public DDFEntities1()
            : base("name=DDFEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DLU_Contact> DLU_Contact { get; set; }
        public virtual DbSet<DLU_Contact_Alt__Addr__Date_Range> DLU_Contact_Alt__Addr__Date_Range { get; set; }
        public virtual DbSet<DLU_Contact_Alt__Address> DLU_Contact_Alt__Address { get; set; }
        public virtual DbSet<DLU_Contact_Business_Relation> DLU_Contact_Business_Relation { get; set; }
        public virtual DbSet<DLU_Contact_Duplicate> DLU_Contact_Duplicate { get; set; }
        public virtual DbSet<DLU_Contact_Industry_Group> DLU_Contact_Industry_Group { get; set; }
        public virtual DbSet<DLU_Contact_Job_Responsibility> DLU_Contact_Job_Responsibility { get; set; }
        public virtual DbSet<DLU_Contact_Mailing_Group> DLU_Contact_Mailing_Group { get; set; }
        public virtual DbSet<DLU_Contact_Profile_Answer> DLU_Contact_Profile_Answer { get; set; }
        public virtual DbSet<DLU_Contact_Value> DLU_Contact_Value { get; set; }
        public virtual DbSet<DLU_Contact_Web_Source> DLU_Contact_Web_Source { get; set; }
    }
}
