//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_eFeriekort_Entry
    {
        public byte[] timestamp { get; set; }
        public string eFeriekort_ID { get; set; }
        public string Employee_No_ { get; set; }
        public int Holiday_Accumulation_Year { get; set; }
        public decimal Pay_entitling_to_vacation_pay { get; set; }
        public decimal Vacation_days_in_total { get; set; }
        public decimal Vacation_pay_percentage { get; set; }
        public decimal Vacation_pay_during_sickness { get; set; }
        public decimal Vacation_pay_per_day { get; set; }
        public decimal Vacation_pay_in_total { get; set; }
        public decimal Settled_AM_contribution { get; set; }
        public decimal Tax_base_vacation_pay { get; set; }
        public decimal Settled_A_tax { get; set; }
        public decimal Net_vacation_pay { get; set; }
        public decimal Surp__stat__hol__pay_FC { get; set; }
        public decimal AM_contribution { get; set; }
        public decimal Tax_base_stat__hol__pay_FC { get; set; }
        public decimal A_tax { get; set; }
        public decimal Surp__stat__hol__pay_FC__net { get; set; }
        public decimal Net_for_vacation_in_total { get; set; }
        public decimal Remaining_vacation_days { get; set; }
        public decimal Remaining_net_vacation_pay { get; set; }
        public decimal Vacation_pay_amount { get; set; }
        public decimal Paid_out_vacation_days { get; set; }
        public decimal Paid_net_vacation_pay { get; set; }
        public string Currency { get; set; }
        public decimal Netto_til_ferie_ialt_ovf_Dage { get; set; }
        public decimal Netto_til_ferie_ialt_ovf_Belob { get; set; }
        public decimal Saldo_overfoert_Dage { get; set; }
        public decimal Saldo_overfoert_Beloeb { get; set; }
        public decimal Netto_feriepenge_Beloeb { get; set; }
        public decimal SH_Fritvalgovs_netto_Belob { get; set; }
        public decimal Netto_til_ferie_ialt_Beloeb { get; set; }
        public decimal Udbetalt_feriedage_indev_aar { get; set; }
        public decimal Udb_feriepenge_inv_aar_Belob { get; set; }
        public decimal Udbetalt_overfoert_ialt_Dage { get; set; }
        public decimal Udbetalt_overfoert_ialt_Belob { get; set; }
        public decimal Perioden_udbetalt_Dage { get; set; }
        public decimal Perioden_udbetalt_Beloeb { get; set; }
    }
}
