//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_HR_Recruitment_Entry
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public int Recruitment_Line_No_ { get; set; }
        public string Cycle_Code { get; set; }
        public int Cycle_Stage { get; set; }
        public string Applicant_No_ { get; set; }
        public string Recruitment_No_ { get; set; }
        public string HR_Professional_Code { get; set; }
        public string Human_Resource_No_ { get; set; }
        public System.DateTime Date_of_Change { get; set; }
        public byte Active { get; set; }
        public System.DateTime Date_Closed { get; set; }
        public decimal Days_Open { get; set; }
        public int Action_Taken { get; set; }
        public decimal Estimated_Cost { get; set; }
        public int Type { get; set; }
        public decimal Completed__ { get; set; }
        public string Close_Recruitment_Line_Code { get; set; }
        public int Previous_Cycle_Stage { get; set; }
        public int Correspondence_Type { get; set; }
        public string Communication_Template_Code { get; set; }
        public int Attachment_No_ { get; set; }
        public int Communication_Log_Entry_No_ { get; set; }
        public string Evaluation_Code { get; set; }
        public string Applicant_Alt__Address_Code { get; set; }
        public string Language_Code { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Time_of_Communication { get; set; }
        public byte Attempt_Failed { get; set; }
        public string To_do_No_ { get; set; }
        public System.DateTime Reference_Date { get; set; }
        public string Communication_Group_Code { get; set; }
        public byte Send_Word_Doc__As_Attmt_ { get; set; }
        public string Contact_Via { get; set; }
        public int Version_No_ { get; set; }
        public string Cycle_Stage_Description { get; set; }
    }
}
