//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Human_Resources_Setup
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public string Employee_Nos_ { get; set; }
        public string Base_Unit_of_Measure { get; set; }
        public string Bank_Branch_No_ { get; set; }
        public string Bank_Account_No_ { get; set; }
        public string Bank_No_ { get; set; }
        public string Bank_Name { get; set; }
        public int Nets_Transfer_No_ { get; set; }
        public string Company_CVR_No_ { get; set; }
        public System.DateTime Allow_Payroll_Posting_from { get; set; }
        public System.DateTime Allow_Payroll_Posting_to { get; set; }
        public string G_L_Journal_Template { get; set; }
        public string G_L_Journal_Batch { get; set; }
        public int Jyske_Bank_Transfer_No_ { get; set; }
        public int G_L_Integration { get; set; }
        public byte Holiday_on_Weekday_Pay_Limit { get; set; }
        public decimal Gratuity_Limit { get; set; }
        public byte Social_Sec__No__as_Empl__No_ { get; set; }
        public string Payroll_Posting_Nos_ { get; set; }
        public byte Activate_Employee_Filter { get; set; }
        public int DA_Maternity___Age { get; set; }
        public int Pay_Reduction_Arrangements { get; set; }
        public int Pay_Reduction_Fraction { get; set; }
        public int Maternity_Arrangement { get; set; }
        public int DA_Maternity_Limit { get; set; }
        public byte Shop_Fl__Begin____Time_Begin { get; set; }
        public byte Time_End____Shop_Fl__End { get; set; }
        public byte Time_Begin____Shop_Fl__Begin { get; set; }
        public byte Last_Shop_Fl__End____Time_End { get; set; }
        public byte Shop_Fl__Begin____Shop_Fl__End { get; set; }
        public System.DateTime End_to_Previous_Day { get; set; }
        public System.DateTime Start_to_Next_Day { get; set; }
        public byte Insert_missing_Begin { get; set; }
        public byte Insert_missing_End { get; set; }
        public byte Accept_missing_Days { get; set; }
        public int Communication_Port { get; set; }
        public byte Daily_Log_File { get; set; }
        public string Time_Stamp_Jnl__Log_Batch_Name { get; set; }
        public string Shop_Fl__St__Jnl__Log_B__Name { get; set; }
        public System.DateTime Stamp_Interval { get; set; }
        public System.DateTime Manual_Stamp_Begin { get; set; }
        public System.DateTime Manual_Stamp_End { get; set; }
        public string Log_File_Location { get; set; }
        public string Terminal_1_Dimension { get; set; }
        public string Terminal_2_Dimension { get; set; }
        public byte Shop_Fl_____Time { get; set; }
        public string eIndkomst_Main_Report_Nos_ { get; set; }
        public string eIndkomst_Rec3101_Nos_ { get; set; }
        public string eIndkomst_Rec4101_Nos_ { get; set; }
        public string eIndkomst_Rec5000_Nos_ { get; set; }
        public string eIndkomst_Files_Storage_Loc_ { get; set; }
        public byte AllowMoreThanOneOpenPPC { get; set; }
        public string Bank_Files_Storage_Loc_ { get; set; }
        public string Pension_Files_Storage_Loc_ { get; set; }
        public string Statistic_Files_Storage_Loc_ { get; set; }
        public string Maternity_Files_Storage_Loc_ { get; set; }
        public string FerieKonto_Files_Storage_Loc_ { get; set; }
        public string Opening_Balance_Journal { get; set; }
        public byte NemKonto_Agreement { get; set; }
        public byte Use_NemKonto_for_all_Empl_ { get; set; }
        public string DA_LO_Development_Fund { get; set; }
        public string DA_LO_Development_Fund_HK { get; set; }
        public string DA_LO_Development_Fund_HORESTA { get; set; }
        public string DA_LO_Dev__Fund_HORESTA_train { get; set; }
        public byte Close_Work_Schedule_at_Term_ { get; set; }
        public string Empl__Time_Stamp_Batch_Name { get; set; }
        public decimal ATP_max { get; set; }
        public byte Use_Lessor_Portal { get; set; }
        public string Company_SE_no_ { get; set; }
        public string Befuldm__LSB_CVR_nr_ { get; set; }
        public string Befuldm__LSB_SE_nr_ { get; set; }
        public int Reporting_Type { get; set; }
        public string Alt__Datasuppl__CVR_SE_no_ { get; set; }
        public byte Use_LIF { get; set; }
        public string Nordea_NemKonto_Branch_No_ { get; set; }
        public byte Foreign_Bank_Transfer { get; set; }
        public int Foreign_Bank_Transfer_Cost { get; set; }
        public string e_Boks_Nos_ { get; set; }
        public System.DateTime Start_to_Previous_Day { get; set; }
        public System.DateTime End_to_Next_Day { get; set; }
        public byte Ref__Date_follow_Daily_Sched_ { get; set; }
        public byte Enable_Ref__Date_to_Prev__Day { get; set; }
        public byte Enable_Ref__Date_to_Next_Day { get; set; }
        public byte Abs_end_date_last_day_pay_per_ { get; set; }
        public byte Pay_reduct__result_of_inactiv_ { get; set; }
        public string Lessor_Online_Support { get; set; }
        public byte Time_reg_w_abs___Shop_Fl_reg_ { get; set; }
        public int Multijob_Calc__Meth_ { get; set; }
        public byte Use_NemRefusion { get; set; }
    }
}
