//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Employee_Filter_Line
    {
        public byte[] timestamp { get; set; }
        public string Employee_Filter_Code { get; set; }
        public string Employee_No_ { get; set; }
        public string Employee_Name { get; set; }
        public string Filter_Name { get; set; }
    }
}
