//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_LIF_Local_Update
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public int Transaction_ID { get; set; }
        public int Table_No_ { get; set; }
        public string Employee_No_ { get; set; }
        public int Type { get; set; }
        public int Field_No_ { get; set; }
        public string Value { get; set; }
        public string Old_Value { get; set; }
        public System.DateTime Modification_Date { get; set; }
        public System.DateTime Modification_Time { get; set; }
        public System.DateTime Transfered_Date { get; set; }
        public System.DateTime Transfered_Time { get; set; }
        public string User_ID { get; set; }
    }
}
