//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_HR_Appl__Questionnaire_Answer
    {
        public byte[] timestamp { get; set; }
        public string Applicant_No_ { get; set; }
        public string Questionnaire_Code { get; set; }
        public int Line_No_ { get; set; }
        public System.DateTime Date { get; set; }
        public int Appl__Questn__Line_No_ { get; set; }
        public int Questionnaire_Priority { get; set; }
        public int Answer_Priority { get; set; }
        public System.DateTime Last_Date_Updated { get; set; }
        public decimal Questions_Answered____ { get; set; }
    }
}
