//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_eFeriekort_Buffer
    {
        public byte[] timestamp { get; set; }
        public int Line_No_ { get; set; }
        public string Valuta { get; set; }
        public decimal Netto_til_ferie_ialt_ovf_Dage { get; set; }
        public decimal Netto_til_ferie_ialt_ovf_Belob { get; set; }
        public decimal Saldo_overfoert_Dage { get; set; }
        public decimal Saldo_overfoert_Beloeb { get; set; }
        public decimal Feriedage_ialt { get; set; }
        public decimal Netto_feriepenge_Beloeb { get; set; }
        public decimal SH_Fritvalgovs_netto_Belob { get; set; }
        public decimal Netto_til_ferie_ialt_Beloeb { get; set; }
        public decimal Feriepenge_pr_dag_Beloeb { get; set; }
        public decimal Udbetalt_feriedage_indev_aar { get; set; }
        public decimal Udb_feriepenge_inv_aar_Belob { get; set; }
        public decimal Udbetalt_overfoert_ialt_Dage { get; set; }
        public decimal Udbetalt_overfoert_ialt_Belob { get; set; }
        public decimal Perioden_udbetalt_Dage { get; set; }
        public decimal Perioden_udbetalt_Beloeb { get; set; }
        public decimal Rest_netto_feriepenge_Beloeb { get; set; }
        public decimal Rest_feriedage { get; set; }
        public string Employee_No_ { get; set; }
        public int Optjeningsaar { get; set; }
    }
}
