//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Login
    {
        public byte[] timestamp { get; set; }
        public string User_ID { get; set; }
        public byte Windows_Login { get; set; }
        public string Windows_Login_ID { get; set; }
        public string Name { get; set; }
    }
}
