//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Column_Transfer
    {
        public byte[] timestamp { get; set; }
        public string Time_Interface_Code { get; set; }
        public int Table_No_ { get; set; }
        public int Line_No_ { get; set; }
        public int Column_No_ { get; set; }
        public string Filter { get; set; }
        public decimal Factor { get; set; }
        public int Field_No_ { get; set; }
    }
}
