//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Danske_Bank_File
    {
        public byte[] timestamp { get; set; }
        public string Request_Id { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public byte Received_Before { get; set; }
        public string Delivery_Number { get; set; }
        public System.DateTime Day { get; set; }
        public System.DateTime Time { get; set; }
        public string CreationTime { get; set; }
    }
}
