//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Field_Validation_Definition
    {
        public byte[] timestamp { get; set; }
        public string Payment_Method { get; set; }
        public string Bank_Bookkeeping_Branch_Code { get; set; }
        public string Field_Name__Validation_ { get; set; }
        public int Line_No_ { get; set; }
        public string Field_Name { get; set; }
        public int Type { get; set; }
        public string Line_ID { get; set; }
        public int Value_of { get; set; }
        public string Formular { get; set; }
        public int Starting_Position { get; set; }
        public int No__of_Positions { get; set; }
        public int Must_be { get; set; }
        public int Expression_Operator { get; set; }
        public string Expression { get; set; }
        public int If_Expression { get; set; }
        public string Error_Message { get; set; }
        public decimal Result { get; set; }
        public byte Valid { get; set; }
        public int Handled_as { get; set; }
        public System.DateTime Last_Date_Modified { get; set; }
        public string Left_Content { get; set; }
        public string Right_Content { get; set; }
        public string Description { get; set; }
        public string Left_Content_Option_Text { get; set; }
        public string Right_Content_Option_Text { get; set; }
    }
}
