//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Outbound_Document
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public int Outbound_Document_Type { get; set; }
        public int Outbound_Document_No_ { get; set; }
        public int Partner_Type { get; set; }
        public string Partner_No_ { get; set; }
        public System.DateTime Date_Sent { get; set; }
        public System.DateTime Time_Sent { get; set; }
        public System.DateTime Date_Processed { get; set; }
        public System.DateTime Time_Processed { get; set; }
        public int Status { get; set; }
        public int No__Resent { get; set; }
        public string Tracking_ID { get; set; }
        public byte Technical_Notif__Sent { get; set; }
        public System.Guid Navision_GUID { get; set; }
    }
}
