//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_HR_Information
    {
        public byte[] timestamp { get; set; }
        public int Table_ID { get; set; }
        public int User_Defined_Field { get; set; }
        public int Field_No_ { get; set; }
        public int Value_Type { get; set; }
        public int Max__Text_Length { get; set; }
        public string Field_Caption { get; set; }
        public byte Range { get; set; }
    }
}
