//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_eFeriekort_Request_Line
    {
        public byte[] timestamp { get; set; }
        public string Batch_ID { get; set; }
        public int Line_No_ { get; set; }
        public string Employee_No_ { get; set; }
        public string Holiday_Start_Date { get; set; }
        public string Days { get; set; }
        public string Holiday_Acc__Year { get; set; }
    }
}
