//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_HR_Outlook_Int__Conflict_Field
    {
        public byte[] timestamp { get; set; }
        public int Error_Log_Entry_No_ { get; set; }
        public string Field_Name { get; set; }
        public string Content { get; set; }
        public string Outlook_Content { get; set; }
        public int Field_Status { get; set; }
        public int Error_Log_Record_Type { get; set; }
        public string Error_Log_Record_No_ { get; set; }
    }
}
