//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Service_Ledger_Entry_VSIFT_4
    {
        public int Type { get; set; }
        public string No_ { get; set; }
        public int Entry_Type { get; set; }
        public byte Moved_from_Prepaid_Acc_ { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public byte Open { get; set; }
        public byte Prepaid { get; set; }
        public Nullable<long> C_Cnt { get; set; }
        public Nullable<decimal> SUM_Amount__LCY_ { get; set; }
        public Nullable<decimal> SUM_Cost_Amount { get; set; }
        public Nullable<decimal> SUM_Quantity { get; set; }
        public Nullable<decimal> SUM_Charged_Qty_ { get; set; }
    }
}
