//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Payment_Method_PM
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public byte Active { get; set; }
        public int Type { get; set; }
        public int Indentation { get; set; }
        public string Search_Name { get; set; }
        public string Totaling { get; set; }
        public System.DateTime Last_Date_Modified { get; set; }
        public byte Manual { get; set; }
        public string Payment_Method_Group_Code { get; set; }
    }
}
