//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Payment_Ledger_Entry_VSIFT_1
    {
        public string Payment_Method { get; set; }
        public string Vendor_No_ { get; set; }
        public string Bank_Account_No___GL_ { get; set; }
        public System.DateTime Date_of_Payment { get; set; }
        public byte Posted { get; set; }
        public Nullable<long> C_Cnt { get; set; }
        public Nullable<decimal> SUM_Amount__LCY_ { get; set; }
        public Nullable<decimal> SUM_Fee__LCY_ { get; set; }
    }
}
