//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Payment_Suggestion_Setup
    {
        public byte[] timestamp { get; set; }
        public string Jnl__Template_Name { get; set; }
        public string Jnl__Batch_Name { get; set; }
        public string Last_Payment_Date_Calc_ { get; set; }
        public byte Find_Payment_Discount { get; set; }
        public byte Summarize_per_Vendor { get; set; }
        public string Posting_Date_Calculation { get; set; }
        public int New_Document_No__Per { get; set; }
        public int Bank_Payment_Type { get; set; }
        public string Recurring_Jnl__Template_Name { get; set; }
        public string Recurring_Journal_Name { get; set; }
        public int Use_Vend__Pmt__Info_ { get; set; }
        public string Description_Template { get; set; }
        public string Fee_Account { get; set; }
        public byte Create_Negative_Amounts { get; set; }
        public byte Ignore_Previous_Application { get; set; }
    }
}
