//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Scribe_Permission_Cache
    {
        public byte[] timestamp { get; set; }
        public string User_ID { get; set; }
        public int Table_No_ { get; set; }
        public string Company_Name { get; set; }
        public byte Read_Permission { get; set; }
        public byte Insert_Permission { get; set; }
        public byte Modify_Permission { get; set; }
        public byte Delete_Permission { get; set; }
    }
}
