//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Calendar_Entry_VSIFT_0
    {
        public int Capacity_Type { get; set; }
        public string No_ { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Starting_Time { get; set; }
        public System.DateTime Ending_Time { get; set; }
        public string Work_Shift_Code { get; set; }
        public Nullable<long> C_Cnt { get; set; }
        public Nullable<decimal> SUM_Capacity__Total_ { get; set; }
        public Nullable<decimal> SUM_Capacity__Effective_ { get; set; }
    }
}
