//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_EP_WP_Request_Table_Action
    {
        public byte[] timestamp { get; set; }
        public string Group_Code { get; set; }
        public string WP_Request_Code { get; set; }
        public int Table_No_ { get; set; }
        public int Header_or_Line { get; set; }
        public int Type { get; set; }
        public int Position { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int Target_WP_Request { get; set; }
        public int HTML_Layout { get; set; }
        public byte Field_Validation_Required { get; set; }
        public byte Restrict_to_Editable { get; set; }
        public int Type_ID { get; set; }
        public int Show_in_Mode { get; set; }
        public int Target_WP_Request_Type { get; set; }
        public int Target_Table_No_ { get; set; }
        public int Caption_ID { get; set; }
        public int Report_ID { get; set; }
        public string Caption { get; set; }
        public string Picture_Code { get; set; }
    }
}
