//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_HR_Search_Line
    {
        public byte[] timestamp { get; set; }
        public string Search_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Human_Resource_No_ { get; set; }
        public string Company_Name { get; set; }
        public string Address { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string Post_Code { get; set; }
        public string Human_Resource_Name { get; set; }
        public string Phone_No_ { get; set; }
        public string Mobile_Phone_No_ { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public int Sex { get; set; }
        public System.DateTime Employment_Date { get; set; }
        public System.DateTime Inactive_Date { get; set; }
        public string Cause_of_Inactivity_Code { get; set; }
        public System.DateTime Termination_Date { get; set; }
        public string Grounds_for_Term__Code { get; set; }
        public string Resource_No_ { get; set; }
        public string Extension { get; set; }
        public string Fax_No_ { get; set; }
        public string Company_E_Mail { get; set; }
        public string Title { get; set; }
        public string Salespers__Purch__Code { get; set; }
        public string Home_Phone_No_ { get; set; }
        public string Home_Mobil_Phone_No_ { get; set; }
        public string Nationality_Code { get; set; }
        public string Civil_Status { get; set; }
        public string Language_Code { get; set; }
        public string Position { get; set; }
        public string HR_Professional_Code { get; set; }
        public string Salutation_Code { get; set; }
        public int Correspondence_Type { get; set; }
        public string Position_Code { get; set; }
        public string Org__Unit_Code { get; set; }
        public string Manager_No_ { get; set; }
        public string Org__Unit_Type_Code { get; set; }
        public string Manager_Name { get; set; }
        public string Org__Unit_Name { get; set; }
        public string Position_Description { get; set; }
        public System.DateTime Seniority_Date { get; set; }
        public System.DateTime Probation_End_Date { get; set; }
        public string Position_Group { get; set; }
        public string Termination_Notice_Code { get; set; }
        public System.DateTime Next_Termination_Date { get; set; }
        public string User_Defined_Field_1 { get; set; }
        public string User_Defined_Field_2 { get; set; }
        public string User_Defined_Field_3 { get; set; }
        public string User_Defined_Field_4 { get; set; }
        public string User_Defined_Field_5 { get; set; }
        public string User_Defined_Field_6 { get; set; }
        public string User_Defined_Field_7 { get; set; }
        public string User_Defined_Field_8 { get; set; }
        public string User_Defined_Field_9 { get; set; }
        public string User_Defined_Field_10 { get; set; }
        public string User_Defined_Field_11 { get; set; }
        public string User_Defined_Field_12 { get; set; }
        public string User_Defined_Field_13 { get; set; }
        public string User_Defined_Field_14 { get; set; }
        public string User_Defined_Field_15 { get; set; }
        public string User_Defined_Field_16 { get; set; }
        public string User_Defined_Field_17 { get; set; }
        public string User_Defined_Field_18 { get; set; }
        public string User_Defined_Field_19 { get; set; }
        public string User_Defined_Field_20 { get; set; }
        public string User_Defined_Field_21 { get; set; }
        public string User_Defined_Field_22 { get; set; }
        public string User_Defined_Field_23 { get; set; }
        public string User_Defined_Field_24 { get; set; }
    }
}
