//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Payroll_Journal_Line_Dimension
    {
        public byte[] timestamp { get; set; }
        public int Table_ID { get; set; }
        public string Journal_Template_Name { get; set; }
        public string Journal_Batch_Name { get; set; }
        public int Journal_Line_No_ { get; set; }
        public int Allocation_Line_No_ { get; set; }
        public string Dimension_Code { get; set; }
        public string Dimension_Value_Code { get; set; }
        public string New_Dimension_Value_Code { get; set; }
    }
}
