//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_DA_DS_Information
    {
        public byte[] timestamp { get; set; }
        public string Employee_No_ { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public string DS_Workplace_Code { get; set; }
        public string DA_Workplace_Code { get; set; }
        public int Employment { get; set; }
        public System.DateTime Employment_Date { get; set; }
        public int Employment_Conditions { get; set; }
        public System.DateTime Employment_Conditions_Date { get; set; }
        public int Job_Status { get; set; }
        public System.DateTime Job_Status_Date { get; set; }
        public int Pay_Frequency { get; set; }
        public decimal Agreed_Upon_Hours__Fixed_ { get; set; }
        public string DS_DA_Total { get; set; }
        public System.DateTime Ending_Date { get; set; }
        public decimal Holiday_Days___Year { get; set; }
        public decimal Holiday_Bonus____ { get; set; }
        public string FA_Agreement { get; set; }
        public string Production_Unit_No_ { get; set; }
        public string Prod__No__DA_Total { get; set; }
        public string New_Salary_Type { get; set; }
        public string Salary_Type { get; set; }
        public string IP0350__Work_Function { get; set; }
        public System.DateTime IP0350__Work_Function_pr_ { get; set; }
    }
}
