//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_ACF_FH_Code_Change
    {
        public byte[] timestamp { get; set; }
        public int Line_No_ { get; set; }
        public string Employee_No_ { get; set; }
        public string Old_FH_Code { get; set; }
        public string New_FH_Code { get; set; }
        public byte Sent_ACF { get; set; }
        public byte Sent_eFeriekort { get; set; }
        public System.DateTime Change_Date { get; set; }
        public System.DateTime Change_Time { get; set; }
        public string User_ID { get; set; }
    }
}
