//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Bank_Account_Statement_Line_VSIFT_0
    {
        public string Bank_Account_No_ { get; set; }
        public string Statement_No_ { get; set; }
        public int Statement_Line_No_ { get; set; }
        public Nullable<long> C_Cnt { get; set; }
        public Nullable<decimal> SUM_Statement_Amount { get; set; }
        public Nullable<decimal> SUM_Difference { get; set; }
    }
}
