//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_HR_Synchronization_Line
    {
        public byte[] timestamp { get; set; }
        public int Source_Table_ID { get; set; }
        public int Source_Field_No_ { get; set; }
        public int Target_Table_ID { get; set; }
        public int Target_Field_No_ { get; set; }
        public byte Synchronize { get; set; }
        public byte Approved { get; set; }
        public string Error_Description { get; set; }
        public byte Warning { get; set; }
    }
}
