//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Rounding_Residual_Buffer
    {
        public byte[] timestamp { get; set; }
        public int Item_Ledger_Entry_No_ { get; set; }
        public decimal Adjusted_Cost { get; set; }
        public decimal Adjusted_Cost__ACY_ { get; set; }
        public byte Completely_Invoiced { get; set; }
    }
}
