//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Pay_Type_Where_Used
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public int TableID { get; set; }
        public string Table_Name { get; set; }
        public string Field_Name { get; set; }
        public string Linje { get; set; }
        public string Pay_Type_No_ { get; set; }
        public string Pay_Type_Description { get; set; }
        public string Key_1 { get; set; }
        public string Key_2 { get; set; }
        public string Key_3 { get; set; }
        public string Key_4 { get; set; }
    }
}
