//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Detailed_Vendor_Ledg__Entry_VSIFT_0
    {
        public int Entry_No_ { get; set; }
        public Nullable<long> C_Cnt { get; set; }
        public Nullable<decimal> SUM_Amount { get; set; }
        public Nullable<decimal> SUM_Amount__LCY_ { get; set; }
        public Nullable<decimal> SUM_Debit_Amount__LCY_ { get; set; }
        public Nullable<decimal> SUM_Credit_Amount__LCY_ { get; set; }
    }
}
