//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_HR_Search_Word_Detail
    {
        public byte[] timestamp { get; set; }
        public int Search_Word_Entry_No_ { get; set; }
        public string No_ { get; set; }
        public string Sub_No_ { get; set; }
        public int Table_Name { get; set; }
        public int Field_No_ { get; set; }
        public int Word_Position { get; set; }
    }
}
