//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Time_Stamp_Jnl__Line
    {
        public byte[] timestamp { get; set; }
        public string Journal_Batch_Name { get; set; }
        public int Line_No_ { get; set; }
        public string Employee_No_ { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Time { get; set; }
        public int Begin_End { get; set; }
        public string Cause_of_Absence_Code { get; set; }
        public string Terminal_Code { get; set; }
        public System.DateTime Reference_Date { get; set; }
        public string Shortcut_Dimension_1_Code { get; set; }
        public string Shortcut_Dimension_2_Code { get; set; }
        public string User_ID { get; set; }
        public string Time_Group_Code { get; set; }
        public string Source_Code { get; set; }
        public string Reason_Code { get; set; }
        public int Sorting { get; set; }
        public string Card_No_ { get; set; }
    }
}
