//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_HR_Report_Buffer
    {
        public byte[] timestamp { get; set; }
        public string User_ID { get; set; }
        public int Report_ID { get; set; }
        public int Entry_No_ { get; set; }
        public int Type { get; set; }
        public string Sort_Code { get; set; }
        public string Human_Resource_No_ { get; set; }
        public string Organization_Unit_Type { get; set; }
        public string Organization_Unit { get; set; }
        public string Position_Code { get; set; }
        public string Employee_Name { get; set; }
        public string Organization_Unit_Name { get; set; }
        public string Text_1 { get; set; }
        public string Text_2 { get; set; }
        public string Text_3 { get; set; }
        public string Text_4 { get; set; }
        public string Text_5 { get; set; }
        public string Text_6 { get; set; }
        public string Text_7 { get; set; }
        public string Text_8 { get; set; }
        public string Text_9 { get; set; }
        public string Text_10 { get; set; }
        public string Text_11 { get; set; }
        public string Text_12 { get; set; }
        public string Text_13 { get; set; }
        public string Text_14 { get; set; }
        public string Text_15 { get; set; }
    }
}
