//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Vendor_Payment_Method
    {
        public byte[] timestamp { get; set; }
        public string Vendor_No_ { get; set; }
        public string Payment_Method { get; set; }
        public byte Standard { get; set; }
        public int Advise_Method { get; set; }
        public string Manual_Advice_Def__Code { get; set; }
        public string Vendor_Number__PBS_ { get; set; }
        public byte Sender_Advice { get; set; }
        public string Recipient_Reference { get; set; }
        public string Pmt__Ident__Def__Code { get; set; }
        public string Bank_Advice_Def__Code { get; set; }
    }
}
