//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Commerce_Portal_Setup
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public string Picture_Target_Folder { get; set; }
        public string Currency_Code { get; set; }
        public string Currency_Description { get; set; }
        public string Country_Code { get; set; }
        public string Country_Name { get; set; }
        public string Language_Code { get; set; }
        public string Language_Name { get; set; }
        public string Picture_Nos_ { get; set; }
        public int Decimal_Symbol { get; set; }
        public string Contact_Nos_ { get; set; }
        public string SQL_Password { get; set; }
        public string Data_Source { get; set; }
        public string Initial_Catalog { get; set; }
        public string SQL_User_ID { get; set; }
        public string Reverse_Auction_Nos_ { get; set; }
        public int Windows_Language_ID { get; set; }
    }
}
