//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_HR_Communication_Log_Entry
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public string Human_Resource_No_ { get; set; }
        public string Applicant_No_ { get; set; }
        public System.DateTime Created { get; set; }
        public string Description { get; set; }
        public int Attachment_No_ { get; set; }
        public string User_ID { get; set; }
        public string Communication_Group_Code { get; set; }
        public string Communication_Template_Code { get; set; }
        public System.DateTime Reference_Date { get; set; }
        public string Recruitment_No_ { get; set; }
        public int Recruitment_Line_No_ { get; set; }
        public int Recruitment_Entry_No_ { get; set; }
        public string Segment_No_ { get; set; }
        public string Cycle_Code { get; set; }
        public System.DateTime Time_of_Communication { get; set; }
        public byte Attempt_Failed { get; set; }
        public int Cycle_Stage { get; set; }
        public string To_do_No_ { get; set; }
        public string HR_Professional_Code { get; set; }
        public int Delivery_Status { get; set; }
        public byte Canceled { get; set; }
        public int Correspondence_Type { get; set; }
        public string Resource_Alt__Address_Code { get; set; }
        public int Closed_Segment_Entry_No_ { get; set; }
        public int Version_No_ { get; set; }
        public int Doc__No__Occurrence { get; set; }
        public byte Send_Word_Docs__as_Attmt_ { get; set; }
        public string Communication_Language_Code { get; set; }
        public byte E_Mail_Logged { get; set; }
        public string Subject { get; set; }
        public int Closed_Recruitment_Entry_No_ { get; set; }
        public byte Postponed { get; set; }
        public System.Guid Mail_GUID { get; set; }
        public string E_Mail { get; set; }
        public int Recipient { get; set; }
        public string Questionnaire_Group_No_ { get; set; }
        public int Questionnaire_Group_Line_No_ { get; set; }
        public string Closed_Questn_Group_No_ { get; set; }
    }
}
