//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_HR_ATS_ID_Buffer
    {
        public byte[] timestamp { get; set; }
        public int Table_ID { get; set; }
        public string Lessor_Portal_ID { get; set; }
    }
}
