//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Comp__Prop___Multilang_
    {
        public byte[] timestamp { get; set; }
        public string Web_Site_Code { get; set; }
        public string Web_Page_No_ { get; set; }
        public string Path { get; set; }
        public string Language_Code { get; set; }
        public string Text { get; set; }
        public int Type { get; set; }
    }
}
