//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_HR_Web_Application_Line
    {
        public byte[] timestamp { get; set; }
        public string Web_Application_Code { get; set; }
        public int Line_No_ { get; set; }
        public int Type { get; set; }
        public string Description { get; set; }
        public int Field_No_ { get; set; }
        public string Field_Caption { get; set; }
        public string Field_Name { get; set; }
        public byte Mandatory { get; set; }
        public byte Table_Relation { get; set; }
    }
}
