//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_HR_Applicant_Competence
    {
        public byte[] timestamp { get; set; }
        public string Applicant_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Competence_Code { get; set; }
        public System.DateTime From_Date { get; set; }
        public System.DateTime To_Date { get; set; }
        public string Institution_Company { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Expiration_Date { get; set; }
        public string Grade_Value { get; set; }
    }
}
