//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Column_Layout
    {
        public byte[] timestamp { get; set; }
        public string Column_Layout_Name { get; set; }
        public int Line_No_ { get; set; }
        public string Column_No_ { get; set; }
        public string Column_Header { get; set; }
        public int Column_Type { get; set; }
        public int Ledger_Entry_Type { get; set; }
        public int Amount_Type { get; set; }
        public string Formula { get; set; }
        public string Comparison_Date_Formula { get; set; }
        public byte Show_Opposite_Sign { get; set; }
        public int Show { get; set; }
        public int Rounding_Factor { get; set; }
        public byte Include_Closing_Date { get; set; }
        public string Comparison_Period_Formula { get; set; }
    }
}
