//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Application_Server_Setup
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Synch__Setup_Code { get; set; }
        public string Request_Setup_Code { get; set; }
        public byte Log_Requests { get; set; }
        public string Mail_Setup_Code { get; set; }
        public byte Log_Synchronization { get; set; }
    }
}
