//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_BA_Db__Cube_Table_Relation
    {
        public byte[] timestamp { get; set; }
        public string BA_Db__Code { get; set; }
        public int BA_Db__Cube_Line_No_ { get; set; }
        public int Line_No_ { get; set; }
        public int Relates_to_Table_No_ { get; set; }
        public int Relates_from_Table_No_ { get; set; }
        public int Relates_from_Field_No_ { get; set; }
    }
}
