//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Warehouse_Entry_VSIFT_5
    {
        public string Item_No_ { get; set; }
        public string Location_Code { get; set; }
        public string Variant_Code { get; set; }
        public string Bin_Type_Code { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public string Lot_No_ { get; set; }
        public string Serial_No_ { get; set; }
        public Nullable<long> C_Cnt { get; set; }
        public Nullable<decimal> SUM_Qty___Base_ { get; set; }
    }
}
