//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Post_Girot_Production_No
    {
        public byte[] timestamp { get; set; }
        public string Ref__No__Post__Bankgirot_ { get; set; }
        public System.DateTime Date { get; set; }
        public int Production_No_ { get; set; }
    }
}
