//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_EP_Caption
    {
        public byte[] timestamp { get; set; }
        public int Caption_ID { get; set; }
        public int Table_No_ { get; set; }
        public int Language_ID { get; set; }
        public string Caption { get; set; }
    }
}
