//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Job_Scheduler_Mgt__Setup
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public byte Log_Scheduler_Actions { get; set; }
        public System.DateTime Shut_Down_Date { get; set; }
        public System.DateTime Shut_Down_Time { get; set; }
        public byte Scheduler_is_Running { get; set; }
        public System.DateTime Last_Date_Modified { get; set; }
        public int Interval_Check__Sec__ { get; set; }
        public string User_ID { get; set; }
        public System.DateTime Login_Time { get; set; }
        public System.DateTime Login_Date { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public System.DateTime Starting_Time { get; set; }
        public string Last_Job_ID_Processed { get; set; }
        public string Last_Message { get; set; }
    }
}
