//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Time_Buffer
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public string Employee_No_ { get; set; }
        public string Time_Type_Code { get; set; }
        public string Time_Group_Code { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Units { get; set; }
        public string Global_Dimension_1_Code { get; set; }
        public string Global_Dimension_2_Code { get; set; }
        public string Cause_of_Absence_Code { get; set; }
        public string User_ID { get; set; }
        public string Pay_Type_No_ { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public string Posting_ID { get; set; }
        public int Origin_Type { get; set; }
        public string Journal_Batch_Name { get; set; }
        public byte Transferred_to_Payroll { get; set; }
        public string Description { get; set; }
        public string Source_Code { get; set; }
        public int Transaction_No_ { get; set; }
        public string Document_No_ { get; set; }
        public int Approval_Status { get; set; }
        public System.DateTime Date_Approved_Rejected { get; set; }
        public string Approved_Rejected_ID { get; set; }
        public System.DateTime Hours_From { get; set; }
        public System.DateTime Hours_To { get; set; }
        public string Prod__Order_No_ { get; set; }
        public string Operation_No_ { get; set; }
        public string Item_No_ { get; set; }
        public string Routing_No_ { get; set; }
        public int Routing_Reference_No_ { get; set; }
        public int Time_Stamp_Entry_Reference { get; set; }
        public string Job_No_ { get; set; }
        public string Phase_Code { get; set; }
        public string Task_Code { get; set; }
        public string Step_Code { get; set; }
        public System.DateTime Work_Schedule_Reference_Date { get; set; }
        public decimal Days { get; set; }
        public System.DateTime From_Date { get; set; }
        public System.DateTime To_Date { get; set; }
        public byte Holds_Dimensions { get; set; }
        public string Full_Name { get; set; }
        public string Phone_No_ { get; set; }
        public string Mobile_Phone_No_ { get; set; }
        public decimal Movement { get; set; }
        public decimal Opening_Balance { get; set; }
        public string Time_Balance_Code { get; set; }
        public byte H_M_for_Time_Account_Statement { get; set; }
        public byte H_M_for_Time_Bal_Acc_Statement { get; set; }
        public int Type { get; set; }
        public System.DateTime Registration_Date { get; set; }
    }
}
