//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_DA_DS_IO_Costs
    {
        public byte[] timestamp { get; set; }
        public string IO_Code { get; set; }
        public string DS_Workplace_Code { get; set; }
        public string DA_Workplace_Code { get; set; }
        public string Description { get; set; }
        public decimal Amount__DKK_ { get; set; }
        public decimal Units { get; set; }
    }
}
