//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Bank_Account_Statistic
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public string Bank_Account_No_ { get; set; }
        public string Name { get; set; }
        public decimal Balance { get; set; }
        public decimal Balance__LCY_ { get; set; }
        public decimal Net_Change { get; set; }
        public decimal Net_Change__LCY_ { get; set; }
        public decimal Balance_after_Posting { get; set; }
        public decimal Balance_after_Posting__LCY_ { get; set; }
        public decimal Min__Balance { get; set; }
        public decimal Internal_Interest { get; set; }
        public string Currency_Code { get; set; }
        public int No__of_Payments { get; set; }
        public int No__of_Collected_Payments { get; set; }
        public decimal Fee__LCY_ { get; set; }
        public decimal Pmt__Disc__Possible { get; set; }
        public decimal Pmt__Disc__Received { get; set; }
    }
}
