//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_eIndkomst_Receipt_Record_0102
    {
        public byte[] timestamp { get; set; }
        public string Main_Report_ID { get; set; }
        public string Basic_Month { get; set; }
        public decimal Bidragspligtig_A_indkomst_13 { get; set; }
        public decimal Bidragsfri_A_indkomst_14 { get; set; }
    }
}
