//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Nets_Buffer
    {
        public byte[] timestamp { get; set; }
        public int Line_No_ { get; set; }
        public int Information_Type { get; set; }
        public string Employee_No_ { get; set; }
        public string Bank_Branch_No_ { get; set; }
        public string Nets_No_ { get; set; }
        public string Payroll_Posting_No_ { get; set; }
        public int Transfer_Type { get; set; }
        public decimal Specified_Amount { get; set; }
        public decimal Units { get; set; }
        public decimal Rate { get; set; }
        public decimal Amount { get; set; }
        public string Identification { get; set; }
        public string Social_Security_No_ { get; set; }
        public string Period_Start { get; set; }
        public string Period_End { get; set; }
        public string Sign { get; set; }
        public string Agreement_No_ { get; set; }
        public System.DateTime Net_Pay_available { get; set; }
        public string Info__Supplier_s_SE_No_ { get; set; }
        public decimal Combined_Amount { get; set; }
        public string Reserve_Code_1 { get; set; }
        public string Reserve_Text_1 { get; set; }
        public string Reserve_Code_2 { get; set; }
        public string Reserve_Text_2 { get; set; }
        public string Reserve_Code_3 { get; set; }
        public string Reserve_Text_3 { get; set; }
        public string Reserve_Code_4 { get; set; }
        public string Reserve_Text_4 { get; set; }
        public string Pension_Type { get; set; }
        public string FileName { get; set; }
        public string PayTypeFilter { get; set; }
        public string InputATPPeriod { get; set; }
        public string InputMaternityPeriod { get; set; }
        public string InputFerieKontoPeriod { get; set; }
        public string InputDAMaternityPeriod { get; set; }
        public string InputEducationPeriod { get; set; }
        public string Company_CVR_SE_No_ { get; set; }
    }
}
