//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Job_Ledger_Entry_VSIFT_6
    {
        public byte Related_to_Budget { get; set; }
        public string Job_No_ { get; set; }
        public int Entry_Type { get; set; }
        public string Phase_Code { get; set; }
        public string Task_Code { get; set; }
        public string Step_Code { get; set; }
        public int Type { get; set; }
        public string No_ { get; set; }
        public string Resource_Group_No_ { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public Nullable<long> C_Cnt { get; set; }
        public Nullable<decimal> SUM_Total_Cost { get; set; }
        public Nullable<decimal> SUM_Total_Price { get; set; }
    }
}
