//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Notification_Setup
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public byte Send_Notifications { get; set; }
        public string Default_Logging_Period { get; set; }
        public int Connection_Type { get; set; }
    }
}
