//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_HR_Vacant_Position
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public string Org__Unit_Type_Code { get; set; }
        public string Organization_Unit_Code { get; set; }
        public string Position_Code { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public decimal No__of_Positions { get; set; }
        public decimal FTE_Factor { get; set; }
    }
}
