//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_eIndkomst_Record_1000
    {
        public byte[] timestamp { get; set; }
        public string Main_Report_ID { get; set; }
        public int Entry_No_ { get; set; }
        public string Reporting_SE_No_ { get; set; }
        public string Reporting_CVR_No_ { get; set; }
        public int Reporting_Type { get; set; }
        public string Payroll_Version { get; set; }
        public string eIndkomst_Version { get; set; }
        public int Test_Marking { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Time { get; set; }
        public string User_ID { get; set; }
        public string Filename { get; set; }
        public byte[] File { get; set; }
    }
}
