//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_HR_Recruitment_Questionnaire
    {
        public byte[] timestamp { get; set; }
        public string Recruitment_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Questionnaire_Code { get; set; }
        public int Priority { get; set; }
        public string Relation_Code { get; set; }
        public byte Mandatory { get; set; }
    }
}
