//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Lessor_Portal_Employee_Buffer
    {
        public byte[] timestamp { get; set; }
        public int Action_Type { get; set; }
        public string Employee_No_ { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Initials { get; set; }
        public string Address { get; set; }
        public string Zipcode { get; set; }
        public string City { get; set; }
        public int Gender { get; set; }
        public string Bank_Branch_No_ { get; set; }
        public string Bank_Account_No_ { get; set; }
        public string Phone_No_ { get; set; }
        public string Phone_No_Work { get; set; }
        public string Mobile_Phone_No_ { get; set; }
        public string Mobile_Phone_No__Work { get; set; }
        public string E_Mail { get; set; }
        public string E_Mail_Work { get; set; }
        public string Job_Title { get; set; }
        public int Settling_Group { get; set; }
        public string Work_Calendar_Code { get; set; }
        public byte E_Mail_Exist { get; set; }
        public string employment_date { get; set; }
        public string date_of_birth { get; set; }
        public string person_se_number { get; set; }
        public string volunteer_tax_rate { get; set; }
        public string termination_date { get; set; }
        public string Lessor_Portal_Empl__No_ { get; set; }
        public string Lessor_Portal_Source_Version { get; set; }
        public string Country { get; set; }
        public string Address2 { get; set; }
        public string Social_Security_No_ { get; set; }
        public string Last_updated { get; set; }
        public string Portal_transaction_ID { get; set; }
        public byte Approved { get; set; }
        public byte Imported { get; set; }
        public string Holiday_Calendar_Code { get; set; }
        public string Middle_Name { get; set; }
        public byte Transfered { get; set; }
        public string Log_Text { get; set; }
        public string Currency_Code { get; set; }
        public string Currency_Country_Code { get; set; }
        public string IBAN { get; set; }
        public string SWIFT_Code { get; set; }
    }
}
