//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_G_L_Entry_VSIFT_2
    {
        public string G_L_Account_No_ { get; set; }
        public string Business_Unit_Code { get; set; }
        public string Global_Dimension_1_Code { get; set; }
        public string Global_Dimension_2_Code { get; set; }
        public int Close_Income_Statement_Dim__ID { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public Nullable<long> C_Cnt { get; set; }
        public Nullable<decimal> SUM_Amount { get; set; }
        public Nullable<decimal> SUM_Debit_Amount { get; set; }
        public Nullable<decimal> SUM_Credit_Amount { get; set; }
        public Nullable<decimal> SUM_Additional_Currency_Amount { get; set; }
        public Nullable<decimal> SUM_Add__Currency_Debit_Amount { get; set; }
        public Nullable<decimal> SUM_Add__Currency_Credit_Amount { get; set; }
    }
}
