//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_LP_Gen__Reg__Journal_Buffer
    {
        public byte[] timestamp { get; set; }
        public int Line_No_ { get; set; }
        public System.DateTime Import_Date { get; set; }
        public System.DateTime Import_Time { get; set; }
        public string registration_transfer_id { get; set; }
        public string registration_transfer_name { get; set; }
        public string company_source_identification { get; set; }
        public string settling_group_source_ID { get; set; }
        public string dimension_1 { get; set; }
        public string dimension_2 { get; set; }
        public string dimension_3 { get; set; }
        public string dimension_4 { get; set; }
        public string dimension_5 { get; set; }
        public string dimension_6 { get; set; }
        public string dimension_7 { get; set; }
        public string dimension_8 { get; set; }
        public string mileage { get; set; }
        public string date { get; set; }
        public string from { get; set; }
        public string to { get; set; }
        public string description { get; set; }
        public string employee_source_identification { get; set; }
        public string code { get; set; }
        public string units { get; set; }
        public string amount { get; set; }
        public string registration_id { get; set; }
        public int Reg__Type { get; set; }
        public byte Cancelling { get; set; }
        public byte Transfered { get; set; }
        public byte bError { get; set; }
        public string ErrorText { get; set; }
    }
}
