//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_BizTalk_Management_Setup
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public byte Notify_Rqst_for_Sales_Qte_Rcvd { get; set; }
        public string Rqst_for_Sales_Qte_User_E_Mail { get; set; }
        public byte Notify_Sales_Order_Rcvd_ { get; set; }
        public string Sales_Order_User_E_Mail { get; set; }
        public byte Notify_Purchase_Quote_Rcvd_ { get; set; }
        public string Purchase_Quote_User_E_Mail { get; set; }
        public byte Notify_Purch_Ord_Cnfmn__Rcvd_ { get; set; }
        public string Purch_Ord_Cnfmn__User_E_Mail { get; set; }
        public byte Notify_Purch_Invoice_Rcvd_ { get; set; }
        public string Purchase_Invoice_User_E_Mail { get; set; }
        public byte Notify_Purchase_Receipt_Rcvd_ { get; set; }
        public string Purchase_Receipt_User_E_Mail { get; set; }
        public byte Notify_Purchase_Cr__Memo_Rcvd_ { get; set; }
        public string Purchase_Cr__Memo_User_E_Mail { get; set; }
        public byte Notify_Product_Catalog_Rcvd_ { get; set; }
        public string Product_Catalog_User_E_Mail { get; set; }
        public byte Send_System_Error_Description { get; set; }
        public string System_Administrator_E_Mail { get; set; }
        public int Maximum_Unsent_Documents { get; set; }
        public int BizTalk_Organization_ID { get; set; }
        public byte Notify_System_Error_Desc__Sent { get; set; }
        public string E_Mail_Profile_Name { get; set; }
        public byte Check_BizTalk_Suspd__Queue { get; set; }
        public int Suspd__Queue_Monitor_Interval { get; set; }
        public int Outbnd__Doc__Monitor_Interval { get; set; }
        public byte Co__Created_on_BizTalk_Server { get; set; }
        public byte Check_Agreement_for_Sent_Doc_ { get; set; }
        public string Rqst__Srv__IP_Address { get; set; }
        public int Rqst__Srv__Port_No_ { get; set; }
        public int Rqst__Srv__Transport_Type { get; set; }
        public int Appln__Srv__Broker_Port_No_ { get; set; }
        public string Appln__Srv__Broker_IP_Address { get; set; }
        public int Create_Company_as_an { get; set; }
        public int BizTalk_Application_ID { get; set; }
        public string BizTalk_Organization_Name { get; set; }
        public string BizTalk_Application_Name { get; set; }
        public byte Use_Encryption { get; set; }
        public byte Hosted_BizTalk_Server { get; set; }
    }
}
