//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Interval_Addition_Journal
    {
        public byte[] timestamp { get; set; }
        public string Add__Holiday_Code { get; set; }
        public string Employee_No_ { get; set; }
        public int Number_of_Months { get; set; }
        public int Alder { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public System.DateTime Seniority_Date { get; set; }
        public byte FV_Setup { get; set; }
        public int Units { get; set; }
        public byte Godkendt { get; set; }
        public decimal Number { get; set; }
    }
}
