//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_HR_LESSOR_ATS_Setup
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public string Account_ID { get; set; }
        public string Company_ID { get; set; }
        public string Portal_ID { get; set; }
        public string Lessor_Portal_URL { get; set; }
        public string Temp__Storage_Location { get; set; }
        public byte Log_Activated { get; set; }
        public int XML_Viewer { get; set; }
        public string Job_Postings_Ping_Filename { get; set; }
        public string Job_Posting_Request_Filename { get; set; }
        public string Job_Posting_Response_Filename { get; set; }
        public string Job_Posting_Ack__Filename { get; set; }
        public string Job_Appl__Ping_Filename { get; set; }
        public string Job_Appl__Ping_Resp__Filename { get; set; }
        public string Job_Appl__Request_Filename { get; set; }
        public string Job_Appl__Response_Filename { get; set; }
        public string Job_Appl__Ack__Filename { get; set; }
        public byte Use_LESSOR_ATS { get; set; }
    }
}
