//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Prod__Order_Routing_Line_VSIFT_0
    {
        public int Status { get; set; }
        public string Prod__Order_No_ { get; set; }
        public int Routing_Reference_No_ { get; set; }
        public string Routing_No_ { get; set; }
        public string Operation_No_ { get; set; }
        public Nullable<long> C_Cnt { get; set; }
        public Nullable<decimal> SUM_Expected_Operation_Cost_Amt_ { get; set; }
        public Nullable<decimal> SUM_Expected_Capacity_Need { get; set; }
        public Nullable<decimal> SUM_Expected_Capacity_Ovhd__Cost { get; set; }
    }
}
