//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Setup_eFeriekort_Employee
    {
        public byte[] timestamp { get; set; }
        public string Employee_No_ { get; set; }
        public string Member_Organization_Code { get; set; }
        public string Association_Code { get; set; }
        public string Holiday_Card_Handling_Code { get; set; }
        public string Free_Text_Field { get; set; }
        public byte Print_Free_Text_Field { get; set; }
    }
}
