//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Smart_Tag_Schedule
    {
        public byte[] timestamp { get; set; }
        public int Day { get; set; }
        public System.DateTime Time { get; set; }
        public System.DateTime Last_Date_Executed { get; set; }
    }
}
