//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Municipality
    {
        public byte[] timestamp { get; set; }
        public string Municipality_Code { get; set; }
        public string Post_Code { get; set; }
        public string City { get; set; }
        public string Municipality_Name { get; set; }
        public string Address { get; set; }
        public string Attention { get; set; }
        public string Phone_No_ { get; set; }
        public string Address2 { get; set; }
    }
}
