//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Payment_Register
    {
        public byte[] timestamp { get; set; }
        public int Number { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Time { get; set; }
        public string User_ID { get; set; }
        public string Bank_Bookkeeping_Branch_Code { get; set; }
        public string Bank { get; set; }
        public string File_Name__Domestic_ { get; set; }
        public string File_Name__Foreign_ { get; set; }
        public string Bank_Reference { get; set; }
    }
}
