//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Notification_Text_Header
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public int Text_No_ { get; set; }
        public string Language_Code { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public System.DateTime Ending_Date { get; set; }
        public byte All_Language_Codes { get; set; }
        public string Subject { get; set; }
    }
}
