//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_eFeriekort_Company_Info_
    {
        public byte[] timestamp { get; set; }
        public string eFeriekort_ID { get; set; }
        public System.DateTime Reporting_Date { get; set; }
        public System.DateTime Reporting_Time { get; set; }
        public string Reporting_CVR_No_ { get; set; }
        public string Reporting_SE_No_ { get; set; }
        public string Company_CVR_No_ { get; set; }
        public string Company_SE_No_ { get; set; }
        public string Payroll_Version { get; set; }
        public string SH_FV_Payroll_Posting_Filter { get; set; }
        public int Max_Acc_Holiday_Year { get; set; }
        public string Reporting_Type { get; set; }
        public string Business_Type { get; set; }
        public string Company_Name { get; set; }
        public string Contact { get; set; }
        public string Add__Reference { get; set; }
        public byte Salary_Earner { get; set; }
        public byte Wage_Earner { get; set; }
        public byte[] XML_Document { get; set; }
        public string Receipt_Text { get; set; }
    }
}
