//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Bank_Fee
    {
        public byte[] timestamp { get; set; }
        public string Bank_Account_No_ { get; set; }
        public string Payment_Method { get; set; }
        public decimal Fee__LCY_ { get; set; }
        public string Alternate_Fee_Account { get; set; }
        public decimal Fee__ { get; set; }
        public decimal Min__Fee__LCY_ { get; set; }
    }
}
