//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Default_Dimension_Priority
    {
        public byte[] timestamp { get; set; }
        public string Source_Code { get; set; }
        public int Table_ID { get; set; }
        public int Priority { get; set; }
    }
}
