//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_eIndkomst_Record_4101
    {
        public byte[] timestamp { get; set; }
        public string Main_Report_ID { get; set; }
        public int Rec2001_Entry_No_ { get; set; }
        public int Entry_No_ { get; set; }
        public string Report_ID { get; set; }
        public string Reference_ID { get; set; }
        public int Canceling_SE_No_ { get; set; }
        public string Social_Security_No_ { get; set; }
        public string Employee_No_ { get; set; }
    }
}
