//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Job_Budget_Entry
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public int Job_Status { get; set; }
        public string Job_No_ { get; set; }
        public int Type { get; set; }
        public string No_ { get; set; }
        public string Phase_Code { get; set; }
        public string Task_Code { get; set; }
        public string Step_Code { get; set; }
        public System.DateTime Date { get; set; }
        public string Resource_Group_No_ { get; set; }
        public decimal Quantity { get; set; }
        public decimal Total_Cost { get; set; }
        public decimal Total_Price { get; set; }
        public string User_ID { get; set; }
        public string Description { get; set; }
        public string Variant_Code { get; set; }
    }
}
