//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_ACF_Payment_Entry
    {
        public byte[] timestamp { get; set; }
        public string ACF_ID { get; set; }
        public string Employee_No_ { get; set; }
        public int Optjeningsaar { get; set; }
        public int Entry_No_ { get; set; }
        public string Udbetalingsformaal { get; set; }
        public System.DateTime Foerste_Feriedag { get; set; }
        public decimal Perioden_udbetalt_Dage { get; set; }
        public decimal Perioden_udbetalt_Beloeb { get; set; }
    }
}
