//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Planning_Component_VSIFT_0
    {
        public string Worksheet_Template_Name { get; set; }
        public string Worksheet_Batch_Name { get; set; }
        public int Worksheet_Line_No_ { get; set; }
        public int Line_No_ { get; set; }
        public Nullable<long> C_Cnt { get; set; }
        public Nullable<decimal> SUM_Cost_Amount { get; set; }
    }
}
