//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_LIF_Remote_System
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public string Server_URL { get; set; }
        public int Proxy_Port { get; set; }
        public string Proxy_Server_URL { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public string Next_Marker { get; set; }
        public byte Use_Proxy { get; set; }
        public byte Active { get; set; }
        public byte eGruppe { get; set; }
        public byte Use_Authorization { get; set; }
        public string User { get; set; }
        public string Password { get; set; }
    }
}
