//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_PDF_Alternative_Field
    {
        public byte[] timestamp { get; set; }
        public int Report_ID { get; set; }
        public int Source_Field_No_ { get; set; }
        public int Field_No_ { get; set; }
        public int Source_Table_No_ { get; set; }
        public int Source_Type { get; set; }
        public byte Use_PDF_Source_Setup { get; set; }
        public int Relation_Table_No_ { get; set; }
        public byte Only_Receiver { get; set; }
        public string Primary_Key { get; set; }
        public byte Email_Active { get; set; }
        public string Field_Value { get; set; }
        public byte Disable_Source_When_Found { get; set; }
        public byte Parameter_Active { get; set; }
    }
}
