//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Detailed_CV_Ledg__Entry_Buffer_VSIFT_4
    {
        public string Customer_No_ { get; set; }
        public int Initial_Document_Type { get; set; }
        public int Document_Type { get; set; }
        public Nullable<long> C_Cnt { get; set; }
        public Nullable<decimal> SUM_Amount { get; set; }
        public Nullable<decimal> SUM_Amount__LCY_ { get; set; }
    }
}
