//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Payroll_Document
    {
        public byte[] timestamp { get; set; }
        public string Employee_No_ { get; set; }
        public int Type { get; set; }
        public string Payroll_Posting_No_ { get; set; }
        public System.DateTime File_Date { get; set; }
        public System.DateTime File_Time { get; set; }
        public byte[] File { get; set; }
        public string User_ID { get; set; }
        public string Filename { get; set; }
        public string Employee_Name { get; set; }
        public int File_Naming { get; set; }
        public byte Payroll_Posting_Revesered { get; set; }
        public System.DateTime Lessor_Portal_Trans__Date { get; set; }
    }
}
