//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_eFeriekort_Request_Header
    {
        public byte[] timestamp { get; set; }
        public string Batch_ID { get; set; }
        public System.DateTime Create_Date { get; set; }
        public System.DateTime Create_Time { get; set; }
        public string Reciver_Type { get; set; }
        public string Reciver_CVR_no_ { get; set; }
        public string Reciver_SE_no_ { get; set; }
        public string System { get; set; }
        public string System_Version { get; set; }
        public System.DateTime Import_Date { get; set; }
        public System.DateTime Import_Time { get; set; }
        public string User_ID { get; set; }
    }
}
