//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_HR_Closed_Questn__Group_Line
    {
        public byte[] timestamp { get; set; }
        public string Questionnaire_Group_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string User_ID { get; set; }
        public string Human_Resource_No_ { get; set; }
        public string Applicant_No_ { get; set; }
        public string HR_Professional_Code { get; set; }
        public System.DateTime Closing_Date { get; set; }
        public string Applicant_Name { get; set; }
        public string Human_Resource_Name { get; set; }
        public string Contact_Alt__Address_Code { get; set; }
        public byte Closed { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public string To_do_No_ { get; set; }
        public string Questionnaire_Code { get; set; }
        public string Questionnaire_Description { get; set; }
        public System.DateTime Deadline_for_Reply { get; set; }
        public int Questionnaire_Priority { get; set; }
        public int Questionnaire_Line_No_ { get; set; }
        public byte Questn__Synchr__Updated { get; set; }
        public int Response_Rate { get; set; }
    }
}
