//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Time_Type_Dimension
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public string Dimension_Code { get; set; }
        public string Dimension_Value_Code { get; set; }
    }
}
