//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Resource_Service_Zone
    {
        public byte[] timestamp { get; set; }
        public string Resource_No_ { get; set; }
        public string Service_Zone_Code { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public string Description { get; set; }
    }
}
