//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_HR_Training_Line
    {
        public byte[] timestamp { get; set; }
        public string Training_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Human_Resource_No_ { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public System.DateTime Ending_Date { get; set; }
        public string Description { get; set; }
        public string Training_Code { get; set; }
        public decimal Price { get; set; }
        public byte Not_Passed { get; set; }
        public string Training_Status_Code { get; set; }
        public decimal Hours_in_total { get; set; }
    }
}
