//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Production_Forecast_Entry_VSIFT_2
    {
        public string Production_Forecast_Name { get; set; }
        public string Item_No_ { get; set; }
        public byte Component_Forecast { get; set; }
        public System.DateTime Forecast_Date { get; set; }
        public string Location_Code { get; set; }
        public Nullable<long> C_Cnt { get; set; }
        public Nullable<decimal> SUM_Forecast_Quantity__Base_ { get; set; }
    }
}
