//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_AdsML_Setup
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public string AdsML_Path { get; set; }
        public string AdsML_Trans__No__Series { get; set; }
        public byte AdsML_Active { get; set; }
        public int Default_Status { get; set; }
        public byte Default_Response_Request { get; set; }
    }
}
