//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLU_Pmt__Ledger_Entry_Pmt__Ident_
    {
        public byte[] timestamp { get; set; }
        public int Vendor_Ledger_Entry_No_ { get; set; }
        public string Payment_Identification { get; set; }
    }
}
