//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDIM__Holding_5802_4
    {
        public int bucket { get; set; }
        public int f5831 { get; set; }
        public int f105 { get; set; }
        public decimal s43 { get; set; }
        public decimal s68 { get; set; }
    }
}
