//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUJ_viewOrderFee
    {
        public byte[] timestamp { get; set; }
        public int OrdreNr { get; set; }
        public int Version { get; set; }
        public int Document_Type { get; set; }
        public int Type { get; set; }
        public int BladId { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
    }
}
