//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
    {
        public byte[] timestamp { get; set; }
        public string Bank_Account_No_ { get; set; }
        public string Account_Statement_No_ { get; set; }
        public decimal Account_Statement_End_Balance { get; set; }
        public System.DateTime Account_Statement_Date { get; set; }
        public decimal Last_Statement___Balance { get; set; }
    }
}
