//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object_Metadata
    {
        public byte[] timestamp { get; set; }
        public int Object_Type { get; set; }
        public int Object_ID { get; set; }
        public byte[] Metadata { get; set; }
        public string Version_List { get; set; }
        public byte[] User_Code { get; set; }
        public System.Guid Object_Key { get; set; }
    }
}
