//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public byte[] timestamp { get; set; }
        public string Profile_ID { get; set; }
        public string Owner_SID { get; set; }
        public string Description { get; set; }
        public int Role_Center_ID { get; set; }
        public byte Default_Role_Center { get; set; }
    }
}
