//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class UGEAVISERNE_307_0
    {
        public int bucket { get; set; }
        public string f4 { get; set; }
        public string f5400 { get; set; }
        public decimal f5 { get; set; }
        public string f1 { get; set; }
        public int f6 { get; set; }
        public string f5401 { get; set; }
        public string f6501 { get; set; }
        public decimal s5 { get; set; }
    }
}
