//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewBlade
    {
        public int BladID { get; set; }
        public string Navn { get; set; }
        public string Adresse { get; set; }
        public Nullable<int> PostNr { get; set; }
        public string Tlf { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public int GruppeID { get; set; }
        public string CVR { get; set; }
        public int MatGodt50 { get; set; }
        public string Homepage { get; set; }
        public bool Overført { get; set; }
    }
}
