//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Holiday_Reporting_Type_SE_No_
    {
        public byte[] timestamp { get; set; }
        public string SE_no_ { get; set; }
        public string Description { get; set; }
        public byte Own_Holiday_Card { get; set; }
    }
}
