//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_EP_Search_Display_Field
    {
        public byte[] timestamp { get; set; }
        public int Table_No_ { get; set; }
        public int Display_Field { get; set; }
        public int Field_No_ { get; set; }
        public int HTML_Layout { get; set; }
        public int Field_Type { get; set; }
    }
}
