//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Recon__Suggestion_Entry
    {
        public byte[] timestamp { get; set; }
        public string Bank_Account_No_ { get; set; }
        public string Bank_Acc__Statement_No_ { get; set; }
        public int Line_No_ { get; set; }
        public int Found_by { get; set; }
        public int Customer_Ledger_Entry_No_ { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public string Customer_No_ { get; set; }
        public string Description { get; set; }
        public byte Currency_Inconsistency { get; set; }
    }
}
