//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Dimension_Code_Amount_Buffer
    {
        public byte[] timestamp { get; set; }
        public string Line_Code { get; set; }
        public string Column_Code { get; set; }
        public decimal Amount { get; set; }
    }
}
