//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Mapping_Lines
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public int Table_no_ { get; set; }
        public int Line_No_ { get; set; }
        public int Field_No_ { get; set; }
        public int Type { get; set; }
        public string Source { get; set; }
        public string Description { get; set; }
        public int KeyIndex { get; set; }
    }
}
