//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Smart_Tag_Setup
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public string Profile_Editor_Path { get; set; }
        public string Dataset_Nos_ { get; set; }
        public string Profile_Nos_ { get; set; }
    }
}
