//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_HR_Sav__App__Search_Crit__Line
    {
        public byte[] timestamp { get; set; }
        public string Search_Criteria_Code { get; set; }
        public int Line_No_ { get; set; }
        public int Action { get; set; }
        public int Type { get; set; }
        public int Table_No_ { get; set; }
        public string View { get; set; }
        public byte Allow_Existing_Applicants { get; set; }
        public byte Ignore_Exclusion { get; set; }
        public int No__of_Filters { get; set; }
    }
}
