//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Work_Schedule_Error_Message
    {
        public byte[] timestamp { get; set; }
        public int Line_No_ { get; set; }
        public int Error_Code { get; set; }
        public string User_ID { get; set; }
        public string Employee_No_ { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public System.DateTime Ending_Date { get; set; }
        public string Work_Schedule_Code { get; set; }
        public string Sequence { get; set; }
    }
}
