//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_VAT_Registration_No__Format
    {
        public byte[] timestamp { get; set; }
        public string Country_Code { get; set; }
        public int Line_No_ { get; set; }
        public string Format { get; set; }
    }
}
