//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Cause_of_Absence_Code_Filter
    {
        public byte[] timestamp { get; set; }
        public int Source_Table { get; set; }
        public string Code { get; set; }
        public string Cause_of_Absence_Codes { get; set; }
        public string COA_Description { get; set; }
        public byte Selected { get; set; }
        public int Sorting { get; set; }
    }
}
