//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Template_Field_Property
    {
        public byte[] timestamp { get; set; }
        public int Table { get; set; }
        public string Code { get; set; }
        public int Line_No_ { get; set; }
        public string Text { get; set; }
        public int No__of_Positions { get; set; }
        public string Place_Before { get; set; }
        public string Place_After { get; set; }
        public string EntireFieldText { get; set; }
        public int Position { get; set; }
        public byte Opposite_Sign { get; set; }
        public byte Truncate_from_Left { get; set; }
    }
}
