//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Acc__Sched__Cell_Value
    {
        public byte[] timestamp { get; set; }
        public int Row_No_ { get; set; }
        public int Column_No_ { get; set; }
        public decimal Value { get; set; }
        public byte Error { get; set; }
        public byte Period_Error { get; set; }
    }
}
