//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_HR_Applicant
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Initials { get; set; }
        public string Job_Title { get; set; }
        public string Search_Name { get; set; }
        public string Address { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string Post_Code { get; set; }
        public string County { get; set; }
        public string Phone_No_ { get; set; }
        public string Mobile_Phone_No_ { get; set; }
        public string E_Mail { get; set; }
        public string Alt__Address_Code { get; set; }
        public byte[] Picture { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public string Social_Security_No_ { get; set; }
        public int Sex { get; set; }
        public string Country_Code { get; set; }
        public System.DateTime Employment_Date { get; set; }
        public string Name { get; set; }
        public System.DateTime Last_Date_Modified { get; set; }
        public string Private_Home_Page { get; set; }
        public string Company_E_Mail { get; set; }
        public string Title { get; set; }
        public string No__Series { get; set; }
        public string Home_Phone_No_ { get; set; }
        public string Home_Mobil_Phone_No_ { get; set; }
        public string Nationality_Code { get; set; }
        public string Civil_Status { get; set; }
        public string Language_Code { get; set; }
        public string HR_Professional_Code { get; set; }
        public string Salutation_Code { get; set; }
        public System.DateTime Last_Time_Modified { get; set; }
        public int Correspondence_Type { get; set; }
        public byte Exclude_from_Recruitment { get; set; }
        public string Termination_Notice_Code { get; set; }
        public System.DateTime Next_Hiring_Date { get; set; }
        public System.DateTime Employment_Date_Old_Employer { get; set; }
        public string Prefix_Name { get; set; }
        public string Prefix_Title { get; set; }
        public string Name_of_Birth { get; set; }
        public string Place_of_Birth { get; set; }
        public string Prefix_Name_of_Birth { get; set; }
        public string Prefix_Title_of_Birth { get; set; }
        public string Native_Country_Code { get; set; }
        public byte Exclude_from_Search { get; set; }
        public string Ethnic_Origin { get; set; }
        public byte Imported { get; set; }
        public string Batch_ID { get; set; }
        public string Applicant_Comment { get; set; }
        public string Applicant_Comment_2 { get; set; }
    }
}
