//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_File_Reporting
    {
        public byte[] timestamp { get; set; }
        public int Type { get; set; }
        public string Filename { get; set; }
        public System.DateTime Creating_Date { get; set; }
        public System.DateTime Creating_Time { get; set; }
        public string Created_By { get; set; }
        public string Main_Report_ID { get; set; }
        public System.DateTime Reporting_Date { get; set; }
        public System.DateTime Reporting_Time { get; set; }
        public string Reported_By { get; set; }
        public byte Reported { get; set; }
    }
}
