//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Cause_of_Absence
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public string DA_Absence_Code { get; set; }
        public int Absence_Type { get; set; }
        public int Unit_Type { get; set; }
        public string Calendar_Code { get; set; }
        public byte Withdraw_Absence { get; set; }
        public byte Absence_Continues { get; set; }
        public byte Time_Account_Statement { get; set; }
        public string Terminal_Text { get; set; }
        public byte Shop_Fl_ { get; set; }
        public string NemRefusion_Code { get; set; }
    }
}
