//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_BA_Db__Dimension_Relation
    {
        public byte[] timestamp { get; set; }
        public string BA_Db__Code { get; set; }
        public int BA_Db__Dimension_Line_No_ { get; set; }
        public int Line_No_ { get; set; }
        public int Relates_from_Table_No_ { get; set; }
        public int Standard_Type { get; set; }
        public int Relates_to_Table_No_ { get; set; }
        public int Numbered_List_Line_No_ { get; set; }
        public string Relates_from_Field_Numbers { get; set; }
        public int Type { get; set; }
    }
}
