//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_BA_Db__Overview_Line
    {
        public byte[] timestamp { get; set; }
        public string BA_Db__Code { get; set; }
        public int Type { get; set; }
        public int Line_No_ { get; set; }
        public int Indentation { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Source_Line_No_ { get; set; }
        public int Source_Parent_Line_No_ { get; set; }
        public int Source_Table_No_ { get; set; }
    }
}
