//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Agreement_Type
    {
        public byte[] timestamp { get; set; }
        public string Agreement_Type_Code { get; set; }
        public string Agreement_Type { get; set; }
        public string BizTalk_Schema_Name { get; set; }
    }
}
