//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_DiMP_StamdataOpsætning
    {
        public byte[] timestamp { get; set; }
        public int Type { get; set; }
        public string Bogføringsgruppe { get; set; }
        public string Betalingsformskode { get; set; }
        public int Udligningsmetode { get; set; }
        public byte Tillad_samlefaktura { get; set; }
        public byte Skattepligtig { get; set; }
        public string Virksomheds_bogføringsgruppe { get; set; }
        public string Moms_virksomheds_bogf_gruppe { get; set; }
        public int Linietype { get; set; }
        public string LinieNummer { get; set; }
        public string Beskrielse1 { get; set; }
        public string Beskrielse2 { get; set; }
        public string Nummerserie_for_nyoprettelser { get; set; }
        public string Standard_rykkerkode { get; set; }
        public string Betalingsbetingelseskode { get; set; }
        public decimal Købsordre_beløbsdiff_grænse { get; set; }
        public string Købsordre_beløbsdiff_konto { get; set; }
        public string Finanskonti_m__oblig__DIMP { get; set; }
        public string F_konto_t__mat_godt_u_faktbart { get; set; }
        public string Annoncør_ID_Anton_Schlecker { get; set; }
        public string F_konto_t__formidl_provision { get; set; }
        public decimal Formidl_provisions__ { get; set; }
        public byte Bogf__købsordre_med_salgsordre { get; set; }
        public byte Bruger_skal_bekræfte_købsbogf_ { get; set; }
        public byte Ovf__autom__indenf__bagatelgr_ { get; set; }
        public string Credit_Text_Code { get; set; }
        public int Fee_Acc__Type { get; set; }
        public string Fee_Acc__No_ { get; set; }
        public decimal FIK_Triviality_Limit { get; set; }
        public byte DIMP_Company { get; set; }
    }
}
