//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Purchases___Payables_Setup
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public int Discount_Posting { get; set; }
        public byte Receipt_on_Invoice { get; set; }
        public byte Invoice_Rounding { get; set; }
        public byte Ext__Doc__No__Mandatory { get; set; }
        public string Vendor_Nos_ { get; set; }
        public string Quote_Nos_ { get; set; }
        public string Order_Nos_ { get; set; }
        public string Invoice_Nos_ { get; set; }
        public string Posted_Invoice_Nos_ { get; set; }
        public string Credit_Memo_Nos_ { get; set; }
        public string Posted_Credit_Memo_Nos_ { get; set; }
        public string Posted_Receipt_Nos_ { get; set; }
        public string Blanket_Order_Nos_ { get; set; }
        public byte Calc__Inv__Discount { get; set; }
        public int Appln__between_Currencies { get; set; }
        public byte Copy_Comments_Blanket_to_Order { get; set; }
        public byte Copy_Comments_Order_to_Invoice { get; set; }
        public byte Copy_Comments_Order_to_Receipt { get; set; }
        public byte Allow_VAT_Difference { get; set; }
        public byte Calc__Inv__Disc__per_VAT_ID { get; set; }
        public string Posted_Return_Shpt__Nos_ { get; set; }
        public byte Copy_Cmts_Ret_Ord__to_Ret_Shpt { get; set; }
        public byte Copy_Cmts_Ret_Ord__to_Cr__Memo { get; set; }
        public string Return_Order_Nos_ { get; set; }
        public byte Return_Shipment_on_Credit_Memo { get; set; }
        public byte Exact_Cost_Reversing_Mandatory { get; set; }
        public string DIMP_Bogførte_fakturanumre { get; set; }
        public string DIMP_Posted_Credit_Memo_Nos_ { get; set; }
    }
}
