//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_PDF_Report_Internal_Email
    {
        public byte[] timestamp { get; set; }
        public int ReportID { get; set; }
        public string Internal_Email_Code { get; set; }
        public int Type { get; set; }
    }
}
