//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_eIndkomst_Record_6003
    {
        public byte[] timestamp { get; set; }
        public string Main_Report_ID { get; set; }
        public int Rec6000_Entry_No_ { get; set; }
        public int Entry_No_ { get; set; }
        public string Field_No_ { get; set; }
        public string Checkmark_Field { get; set; }
        public string Payroll_Posting_No_ { get; set; }
        public System.DateTime Pay_Period_Starting_Date { get; set; }
        public System.DateTime Pay_Period_Ending_Date { get; set; }
        public System.DateTime Net_Pay_Available { get; set; }
        public int Payed_Advance_Behind { get; set; }
        public int Greenland_Municipality { get; set; }
        public string Employment_Code { get; set; }
        public string Social_Security_No_ { get; set; }
        public string Employee_No_ { get; set; }
        public string Income_Type__Code_68_ { get; set; }
        public string Production_Unit_No_ { get; set; }
        public byte Reversed { get; set; }
        public System.DateTime eIndkomst_Date { get; set; }
    }
}
