//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_NemRefusion_Buffer
    {
        public byte[] timestamp { get; set; }
        public int Line_No { get; set; }
        public System.DateTime Import_Date { get; set; }
        public System.DateTime Import_Time { get; set; }
        public string info_response_already_received { get; set; }
        public string events_only { get; set; }
        public string sick_leave_id { get; set; }
        public string sick_leave_type { get; set; }
        public string absence_start_date { get; set; }
        public string company_source_identification { get; set; }
        public byte Error { get; set; }
        public string employee_source_identification { get; set; }
        public string Employee_No_ { get; set; }
        public byte Info_Response_Sent { get; set; }
        public string registration_source_id { get; set; }
        public string registration_id { get; set; }
        public string Log_Entry_Batch_ID { get; set; }
        public int Report_Batch_ID { get; set; }
    }
}
