//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_HR_Organization_Plan
    {
        public byte[] timestamp { get; set; }
        public string Plan_Name { get; set; }
        public string Org__Unit_Type_Code { get; set; }
        public string Organization_Unit_Code { get; set; }
        public int Line_No_ { get; set; }
        public string Description { get; set; }
        public int Level { get; set; }
        public System.DateTime Start_Date { get; set; }
    }
}
