//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Purch__Documents_PM
    {
        public byte[] timestamp { get; set; }
        public int Number { get; set; }
        public int Origination { get; set; }
        public int Document_Type { get; set; }
        public string Document_No_ { get; set; }
        public string Vendor_No_ { get; set; }
        public int Entry_No_ { get; set; }
    }
}
