//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_EP_WP_Request_Table_Tab
    {
        public byte[] timestamp { get; set; }
        public string Group_Code { get; set; }
        public string WP_Request_Code { get; set; }
        public int Table_No_ { get; set; }
        public int Header_or_Line { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int No__of_Columns { get; set; }
        public int Position { get; set; }
        public int Caption_ID { get; set; }
        public string Caption { get; set; }
    }
}
