//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_eIndkomst_Record_2001
    {
        public byte[] timestamp { get; set; }
        public string Main_Report_ID { get; set; }
        public int Entry_No_ { get; set; }
        public string Company_SE_No_ { get; set; }
        public string Company_Stopping { get; set; }
        public string Currency { get; set; }
    }
}
