//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Time_Buffer_VSIFT_1
    {
        public string Employee_No_ { get; set; }
        public System.DateTime Date { get; set; }
        public string Time_Type_Code { get; set; }
        public string Time_Group_Code { get; set; }
        public Nullable<long> C_Cnt { get; set; }
        public Nullable<decimal> SUM_Units { get; set; }
    }
}
