//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Tax_Card_Reg__Journal_Line
    {
        public byte[] timestamp { get; set; }
        public string Journal_Name { get; set; }
        public string Employee_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Social_Security_No_ { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public string Employee_Name { get; set; }
        public System.DateTime Employment_Date { get; set; }
        public System.DateTime Termination_Date { get; set; }
        public int Tax_Deductible_Type { get; set; }
        public int Type { get; set; }
        public string Main_Report_ID { get; set; }
        public System.DateTime Send_Date { get; set; }
        public System.DateTime Send_Time { get; set; }
        public string Sending_User_ID { get; set; }
        public System.DateTime Receiving_Date { get; set; }
        public System.DateTime Receiving_Time { get; set; }
        public string Receiving_User_ID { get; set; }
    }
}
