//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Scribe_User_Authentication
    {
        public byte[] timestamp { get; set; }
        public string User_ID { get; set; }
        public int Authentication { get; set; }
        public string Login_SID { get; set; }
        public string Password { get; set; }
        public System.DateTime Last_Active { get; set; }
    }
}
