//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Whse__Cross_Dock_Opportunity_VSIFT_1
    {
        public string Item_No_ { get; set; }
        public string Location_Code { get; set; }
        public Nullable<long> C_Cnt { get; set; }
        public Nullable<decimal> SUM_Qty__to_Cross_Dock { get; set; }
        public Nullable<decimal> SUM_Qty__to_Cross_Dock__Base_ { get; set; }
        public Nullable<decimal> SUM_Qty__Needed { get; set; }
        public Nullable<decimal> SUM_Qty__Needed__Base_ { get; set; }
    }
}
