//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Time_Balance
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public System.DateTime Last_Date_Modified { get; set; }
        public decimal Factor { get; set; }
        public byte Time_Account_Statement { get; set; }
        public string Terminal_Text { get; set; }
        public string Terminal_Sequence { get; set; }
        public byte H_M_for_Time_Account_Statement { get; set; }
        public byte H_M_for_Time_Bal_Acc_Statement { get; set; }
    }
}
