//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Sickleave_Absence_Entry
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public string Employee_No_ { get; set; }
        public int Employee_Absence_Entry_No_ { get; set; }
        public System.DateTime From_Date { get; set; }
        public System.DateTime To_Date { get; set; }
        public string Cause_of_Absence_Code { get; set; }
        public string Description { get; set; }
        public decimal Days { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public string Work_Calendar_Code { get; set; }
        public string Employee_Name { get; set; }
        public int Absence_Type { get; set; }
        public string DA_Absence_Code { get; set; }
        public decimal Hours { get; set; }
        public byte Holiday_Card { get; set; }
        public int Holiday_Accumulation_Year { get; set; }
        public byte Holiday_Bonus { get; set; }
        public byte Modified { get; set; }
        public string Journal_Name { get; set; }
        public System.DateTime Reported_Absence { get; set; }
        public System.DateTime Repayment_Applied_for { get; set; }
        public System.DateTime Original_From_Date { get; set; }
        public int Sickleave_Application_Code { get; set; }
        public byte Closed { get; set; }
        public byte Not_Sickleave { get; set; }
        public byte Rejected { get; set; }
    }
}
