//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Bank_Pmt__Prioritizing_Line_VSIFT_0
    {
        public string Jnl__Template_Name { get; set; }
        public string Jnl__Batch_Name { get; set; }
        public string Bank_Account_No_ { get; set; }
        public Nullable<long> C_Cnt { get; set; }
        public Nullable<decimal> SUM_Amount_Available__LCY_ { get; set; }
    }
}
