//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_eIndkomst_Buffer_Record_5000
    {
        public byte[] timestamp { get; set; }
        public string Payroll_Posting_No_ { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public System.DateTime Ending_Date { get; set; }
        public int Income_Type { get; set; }
        public int Greenland_Municipality { get; set; }
        public byte Terminated_Employee { get; set; }
    }
}
