//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Medlem
    {
        public byte[] timestamp { get; set; }
        public string Kundenr_ { get; set; }
        public string Nummer { get; set; }
        public string Navn { get; set; }
        public string Navn_2 { get; set; }
        public System.DateTime Indmeldelsesdato { get; set; }
        public System.DateTime Udmeldelsesdato { get; set; }
        public decimal Antal_timer { get; set; }
        public string Bemærkning { get; set; }
    }
}
