//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_HR_Seniority_Statistic_Intvl_
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public int Min__Value { get; set; }
        public int Max__Value { get; set; }
        public string Description { get; set; }
        public int Total_Column { get; set; }
        public int Column_1 { get; set; }
        public int Column_2 { get; set; }
        public int Column_3 { get; set; }
        public int Column_4 { get; set; }
        public int Column_5 { get; set; }
        public int Column_6 { get; set; }
        public int Column_7 { get; set; }
        public int Column_8 { get; set; }
        public int Column_9 { get; set; }
        public int Column_10 { get; set; }
        public int Column_11 { get; set; }
        public int Column_12 { get; set; }
        public int Column_13 { get; set; }
    }
}
