//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_HR_Human_Resource_Relative
    {
        public byte[] timestamp { get; set; }
        public string Human_Resource_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Relative_Code { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public string Phone_No_ { get; set; }
        public string Address { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string Post_Code { get; set; }
        public string County { get; set; }
        public string Mobile_Phone_No_ { get; set; }
        public string E_Mail { get; set; }
        public string Country_Code { get; set; }
        public int Sex { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
    }
}
