//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_HR_Error_Message
    {
        public byte[] timestamp { get; set; }
        public int Line_No_ { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Time { get; set; }
        public string Human_Resource_No_ { get; set; }
        public string Applicant_No_ { get; set; }
        public string HR_Professional_Code { get; set; }
        public string To_do_No_ { get; set; }
        public System.DateTime Due_Date { get; set; }
        public string Activity_Code { get; set; }
        public int Step_No_ { get; set; }
        public string User_ID { get; set; }
    }
}
