//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_HR_Human_Resource
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Initials { get; set; }
        public string Job_Title { get; set; }
        public string Search_Name { get; set; }
        public string Address { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string Post_Code { get; set; }
        public string County { get; set; }
        public string Phone_No_ { get; set; }
        public string Mobile_Phone_No_ { get; set; }
        public string E_Mail { get; set; }
        public string Alt__Address_Code { get; set; }
        public System.DateTime Alt__Address_Start_Date { get; set; }
        public System.DateTime Alt__Address_End_Date { get; set; }
        public byte[] Picture { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public string Social_Security_No_ { get; set; }
        public string Union_Code { get; set; }
        public string Union_Membership_No_ { get; set; }
        public int Sex { get; set; }
        public string Country_Code { get; set; }
        public System.DateTime Employment_Date { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public System.DateTime Inactive_Date { get; set; }
        public string Cause_of_Inactivity_Code { get; set; }
        public System.DateTime Termination_Date { get; set; }
        public string Grounds_for_Term__Code { get; set; }
        public string Global_Dimension_1_Code { get; set; }
        public string Global_Dimension_2_Code { get; set; }
        public string Resource_No_ { get; set; }
        public System.DateTime Last_Date_Modified { get; set; }
        public string Extension { get; set; }
        public string Pager { get; set; }
        public string Fax_No_ { get; set; }
        public string Company_E_Mail { get; set; }
        public string Title { get; set; }
        public string Salespers__Purch__Code { get; set; }
        public string No__Series { get; set; }
        public string Home_Phone_No_ { get; set; }
        public string Home_Mobil_Phone_No_ { get; set; }
        public string Nationality_Code { get; set; }
        public string Civil_Status { get; set; }
        public string Room { get; set; }
        public string Language_Code { get; set; }
        public string Position { get; set; }
        public string HR_Professional_Code { get; set; }
        public string Organization_Relation_Code { get; set; }
        public string Salutation_Code { get; set; }
        public string Search_E_Mail { get; set; }
        public int Version_No_ { get; set; }
        public System.DateTime Last_Time_Modified { get; set; }
        public int Correspondence_Type { get; set; }
        public byte Exclude_from_Segment { get; set; }
        public string Manager_No_ { get; set; }
        public string Org__Unit_Type_Code { get; set; }
        public System.DateTime Seniority_Date { get; set; }
        public System.DateTime Probation_End_Date { get; set; }
        public string Private_Home_Page { get; set; }
        public string Termination_Notice_Code { get; set; }
        public System.DateTime Next_Termination_Date { get; set; }
        public string Prefix_Name { get; set; }
        public string Prefix_Title { get; set; }
        public string Name_of_Birth { get; set; }
        public string Place_of_Birth { get; set; }
        public string Prefix_Name_of_Birth { get; set; }
        public string Prefix_Title_of_Birth { get; set; }
        public string Native_Country_Code { get; set; }
        public byte Exclude_from_Search { get; set; }
        public System.DateTime Next_Birthday { get; set; }
        public int Synchronization_Source { get; set; }
        public string Ethnic_Origin { get; set; }
        public string User_Defined_Field_1 { get; set; }
        public string User_Defined_Field_2 { get; set; }
        public string User_Defined_Field_3 { get; set; }
        public string User_Defined_Field_4 { get; set; }
        public string User_Defined_Field_5 { get; set; }
        public string User_Defined_Field_6 { get; set; }
        public string User_Defined_Field_7 { get; set; }
        public string User_Defined_Field_8 { get; set; }
        public string User_Defined_Field_9 { get; set; }
        public string User_Defined_Field_10 { get; set; }
        public string User_Defined_Field_11 { get; set; }
        public string User_Defined_Field_12 { get; set; }
        public string User_Defined_Field_13 { get; set; }
        public string User_Defined_Field_14 { get; set; }
        public string User_Defined_Field_15 { get; set; }
        public string User_Defined_Field_16 { get; set; }
        public string User_Defined_Field_17 { get; set; }
        public string User_Defined_Field_18 { get; set; }
        public string User_Defined_Field_19 { get; set; }
        public string User_Defined_Field_20 { get; set; }
        public string User_Defined_Field_21 { get; set; }
        public string User_Defined_Field_22 { get; set; }
        public string User_Defined_Field_23 { get; set; }
        public string User_Defined_Field_24 { get; set; }
        public System.DateTime Inactive_Until__Date_ { get; set; }
    }
}
