//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Omdøbningslinie1
    {
        public byte[] timestamp { get; set; }
        public int Kartotek { get; set; }
        public string Nummer { get; set; }
        public string Tekst { get; set; }
        public string Omdøbes_til { get; set; }
        public string Oprettet_af { get; set; }
        public System.DateTime Oprettet_d_ { get; set; }
        public System.DateTime Oprettet_kl_ { get; set; }
        public byte Omdøbt { get; set; }
        public string Omdøbt_af { get; set; }
        public System.DateTime Omdøbt_d_ { get; set; }
        public System.DateTime Omdøbt_start_kl_ { get; set; }
        public System.DateTime Omdøbt_slut_kl_ { get; set; }
    }
}
