//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Extended_Information
    {
        public byte[] timestamp { get; set; }
        public string Context { get; set; }
        public string Context_Id { get; set; }
        public string Web_Service { get; set; }
        public string Web_Service_Id { get; set; }
        public string Production_No_ { get; set; }
        public string Municipality_Code { get; set; }
        public string County_Code { get; set; }
        public string Mobile_Phone_No_ { get; set; }
    }
}
