//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Res__Ledger_Entry_VSIFT_3
    {
        public int Entry_Type { get; set; }
        public byte Chargeable { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public string Resource_Group_No_ { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public Nullable<long> C_Cnt { get; set; }
        public Nullable<decimal> SUM_Quantity { get; set; }
        public Nullable<decimal> SUM_Total_Cost { get; set; }
        public Nullable<decimal> SUM_Total_Price { get; set; }
        public Nullable<decimal> SUM_Quantity__Base_ { get; set; }
    }
}
