//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Template_Merge_Field
    {
        public byte[] timestamp { get; set; }
        public string KEY { get; set; }
        public int Date { get; set; }
        public int Time { get; set; }
        public int User_Name { get; set; }
        public int Vendor_Address_1 { get; set; }
        public int Vendor_Address_2 { get; set; }
        public int Vendor_Address_3 { get; set; }
        public int Vendor_Address_4 { get; set; }
        public int Vendor_Address_5 { get; set; }
        public int Vendor_Address_6 { get; set; }
        public int Vendor_Address_7 { get; set; }
        public int Vendor_Address_8 { get; set; }
        public int Company_Address_1 { get; set; }
        public int Company_Address_2 { get; set; }
        public int Company_Address_3 { get; set; }
        public int Company_Address_4 { get; set; }
        public int Company_Address_5 { get; set; }
        public int Company_Address_6 { get; set; }
        public int Our_Account_No__Text { get; set; }
        public int Payment_Method_Description { get; set; }
    }
}
