//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_MultiJob_Entry_Buffer
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public string Employee_No_ { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Time { get; set; }
        public int Begin_End { get; set; }
        public string Global_Dimension_1_Code { get; set; }
        public string Global_Dimension_2_Code { get; set; }
        public string Prod__Order_No_ { get; set; }
        public string Item_No_ { get; set; }
        public byte Finished { get; set; }
        public decimal Output_Quantity { get; set; }
        public string Work_Center_Machine_Center_No_ { get; set; }
        public string Operation_No_ { get; set; }
        public int Sorting { get; set; }
        public System.DateTime Reference_Date { get; set; }
        public decimal Scrapped_Quantity { get; set; }
        public string Scrap_Code { get; set; }
        public string Stop_Code { get; set; }
        public int Type { get; set; }
        public int Shop_Fl__Stamp_Entry_No_ { get; set; }
        public byte MultiJob { get; set; }
        public byte Calculated { get; set; }
        public System.DateTime From_Time { get; set; }
        public System.DateTime To_Time { get; set; }
        public System.DateTime H_M { get; set; }
        public decimal Hours { get; set; }
        public int Routing_Reference_No_ { get; set; }
        public string Routing_No_ { get; set; }
        public byte Error { get; set; }
        public System.DateTime Break_Time { get; set; }
        public int MultiJobBatch { get; set; }
        public byte Setup { get; set; }
        public byte Secondary { get; set; }
        public string Serial_No_ { get; set; }
        public string Lot_No_ { get; set; }
    }
}
