//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Service_Hour
    {
        public byte[] timestamp { get; set; }
        public int Service_Contract_Type { get; set; }
        public string Service_Contract_No_ { get; set; }
        public int Day { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public System.DateTime Starting_Time { get; set; }
        public System.DateTime Ending_Time { get; set; }
        public byte Valid_on_Holidays { get; set; }
    }
}
