//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_PDF_Attachment_Log
    {
        public byte[] timestamp { get; set; }
        public int Log_Entry_No_ { get; set; }
        public int Entry_No_ { get; set; }
        public int Source_Type { get; set; }
        public string Source_No_ { get; set; }
        public string Filename { get; set; }
        public string Long_Filename { get; set; }
        public byte Main_Document { get; set; }
        public byte[] PDF_Document { get; set; }
        public byte Merge_into_Main_Document { get; set; }
        public string PDF_Location { get; set; }
        public byte Delete_After_Sending { get; set; }
        public int Report_ID { get; set; }
        public int Table_ID { get; set; }
        public string Record_View { get; set; }
    }
}
