//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Bank_Account
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public string Name { get; set; }
        public string Search_Name { get; set; }
        public string Name_2 { get; set; }
        public string Address { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string Contact { get; set; }
        public string Phone_No_ { get; set; }
        public string Telex_No_ { get; set; }
        public string Bank_Account_No_ { get; set; }
        public string Transit_No_ { get; set; }
        public string Territory_Code { get; set; }
        public string Global_Dimension_1_Code { get; set; }
        public string Global_Dimension_2_Code { get; set; }
        public string Chain_Name { get; set; }
        public decimal Min__Balance { get; set; }
        public string Bank_Acc__Posting_Group { get; set; }
        public string Currency_Code { get; set; }
        public string Language_Code { get; set; }
        public int Statistics_Group { get; set; }
        public string Our_Contact_Code { get; set; }
        public string Country_Code { get; set; }
        public decimal Amount { get; set; }
        public byte Blocked { get; set; }
        public string Last_Statement_No_ { get; set; }
        public System.DateTime Last_Date_Modified { get; set; }
        public string Fax_No_ { get; set; }
        public string Telex_Answer_Back { get; set; }
        public byte[] Picture { get; set; }
        public string Post_Code { get; set; }
        public string County { get; set; }
        public string Last_Check_No_ { get; set; }
        public decimal Balance_Last_Statement { get; set; }
        public string Bank_Branch_No_ { get; set; }
        public string E_Mail { get; set; }
        public string Home_Page { get; set; }
        public string No__Series { get; set; }
        public int Check_Report_ID { get; set; }
        public string IBAN { get; set; }
        public string SWIFT_Code { get; set; }
        public string Bank_Code { get; set; }
        public string Sender_Ref__def_Code { get; set; }
        public decimal Internal_Interest { get; set; }
        public string IBAN__PM_ { get; set; }
        public string BIC__SWIFT_Address_ { get; set; }
        public decimal Allowed_Bal__when_Prioritizing { get; set; }
        public string Ref__No___Post__Bankgirot_ { get; set; }
        public string Cash_Rcpt__Jnl__Temp__Name { get; set; }
        public string Cash_Rcpt__Jnl__Batch_Name { get; set; }
        public string Gen__Jnl__Template_Name { get; set; }
        public string Gen__Jnl__Batch_Name { get; set; }
        public decimal Diff__before_Auto__Suggestion { get; set; }
    }
}
