//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Payroll_Posting
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public System.DateTime Ending_Date { get; set; }
        public System.DateTime Net_Pay_available { get; set; }
        public System.DateTime Bank_Date { get; set; }
        public int Tax_Year { get; set; }
        public string User_ID { get; set; }
        public int From_Entry_No_ { get; set; }
        public int To_Entry_No_ { get; set; }
        public string Description { get; set; }
        public byte Reversed { get; set; }
        public byte Posted { get; set; }
        public byte Holiday_Calculation { get; set; }
        public byte Conversion { get; set; }
        public string Employee_No_ { get; set; }
        public int Pay_Frequency { get; set; }
        public int Type { get; set; }
        public int Payed_Advance_Behind { get; set; }
        public int Pay_Week { get; set; }
        public byte Include_Recurring_Journal { get; set; }
        public byte Include_Period_Journal { get; set; }
        public byte Include_General_Reg__Journal { get; set; }
        public byte Include_Pay_Type_Journal { get; set; }
        public byte Include_Automatic_Pay_Types { get; set; }
        public byte Include_Absence_Journal { get; set; }
        public byte Include_Misc__Articles { get; set; }
        public byte Include_Garnishment_and_Loan { get; set; }
        public byte Include_Opening_Balance { get; set; }
        public string Reverse_Payroll_Posting_No_ { get; set; }
        public byte Reverse_Posting { get; set; }
        public string Document_No_ { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public string G_L_Journal_Batch { get; set; }
        public byte Payroll_Calculation { get; set; }
        public string No__Series { get; set; }
        public System.DateTime Absence_Ending_Date { get; set; }
        public string Main_Report_ID { get; set; }
        public byte Tested { get; set; }
        public byte Payroll_Posting_Reversed { get; set; }
        public string Report_ID { get; set; }
        public string Server_Type { get; set; }
        public string Navision_Version { get; set; }
        public string Payroll_Version { get; set; }
        public int Num__of_Empl__in_Pay__Posting { get; set; }
        public int Number_of_Employees_Total { get; set; }
        public int Number_of_Pay_Entries_Total { get; set; }
        public string Elapsed_Time { get; set; }
        public string Payroll_Posting_Time { get; set; }
        public byte Lessor_Portal_Complete { get; set; }
        public byte Lessor_Portal_Transfered { get; set; }
        public byte Lessor_Portal_Tested { get; set; }
        public byte Include_Add__Holidays { get; set; }
        public byte Include_Holiday_Accumulation { get; set; }
    }
}
