//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Country
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string EU_Country_Code { get; set; }
        public string Intrastat_Code { get; set; }
        public int Address_Format { get; set; }
        public int Contact_Address_Format { get; set; }
        public string OIOXML_Country_Code { get; set; }
    }
}
