//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_eIndkomst_Tax_Card_Buffer
    {
        public byte[] timestamp { get; set; }
        public string Employee_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Social_Security_No_ { get; set; }
        public System.DateTime Valid_From_Date { get; set; }
        public string Employer_SE_No_ { get; set; }
        public string Payroll_service_bureau_SE_No_ { get; set; }
        public System.DateTime Date_of_Tax_Card_Run { get; set; }
        public int Tax_Card_Type { get; set; }
        public int Income_Year { get; set; }
        public int Max__A_Income_non_Taxable { get; set; }
        public int Tax__ { get; set; }
        public int Daily_Allowance { get; set; }
        public int Weekly_Allowance { get; set; }
        public int Fortnightly_Allowance { get; set; }
        public int Monthly_Allowance { get; set; }
        public System.DateTime Receiving_Date { get; set; }
        public System.DateTime Receiving_Time { get; set; }
        public int Extra_Tax__ { get; set; }
        public string Run_ID { get; set; }
        public int Non_Taxable_Balance { get; set; }
        public int eTax_Line_No_ { get; set; }
        public string Batch_No_ { get; set; }
    }
}
