//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Payment_Method_Group
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Pmt__Ident__Def__Code { get; set; }
        public System.DateTime Last_Date_Modified { get; set; }
        public string Manual_Advice_Def__Code { get; set; }
        public byte Sender_Advice { get; set; }
        public int Advise_Method { get; set; }
        public string Bank_Advice_Def__Code { get; set; }
    }
}
