//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Employee_Template_Rate
    {
        public byte[] timestamp { get; set; }
        public string Employee_Template_Code { get; set; }
        public string Pay_Type_No_ { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public int Minimum_Age { get; set; }
        public decimal Rate { get; set; }
        public System.DateTime Ending_Date { get; set; }
        public int Output { get; set; }
    }
}
