//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_X_tblBlade
    {
        public byte[] timestamp { get; set; }
        public int BladID { get; set; }
        public string GeoKode { get; set; }
        public int KortNr { get; set; }
        public string DelOmr { get; set; }
        public string Navn { get; set; }
        public string Adresse { get; set; }
        public string PostNr { get; set; }
        public string Tlf { get; set; }
        public string Fax { get; set; }
        public decimal Oplag { get; set; }
        public string Ugedag { get; set; }
        public decimal mmPris { get; set; }
        public decimal Rabat { get; set; }
        public int Antal_13 { get; set; }
        public decimal Antal_13_ { get; set; }
        public string RegText { get; set; }
        public byte DeAktiveret { get; set; }
        public string Email { get; set; }
        public byte DelMail { get; set; }
        public byte Overført { get; set; }
        public System.DateTime Overført_den { get; set; }
        public System.DateTime Overført_Kl_ { get; set; }
        public int GruppeID { get; set; }
        public string CVR_nr_ { get; set; }
        public byte Materialegodtgørelse_50 { get; set; }
    }
}
