//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Interaction_Log_Entry_VSIFT_1
    {
        public string Contact_Company_No_ { get; set; }
        public string Contact_No_ { get; set; }
        public System.DateTime Date { get; set; }
        public byte Postponed { get; set; }
        public Nullable<long> C_Cnt { get; set; }
        public Nullable<decimal> SUM_Cost__LCY_ { get; set; }
        public Nullable<decimal> SUM_Duration__Min__ { get; set; }
    }
}
