//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Lessor_Portal_Balance_Buffer
    {
        public byte[] timestamp { get; set; }
        public int Line_No_ { get; set; }
        public string Employee_Source_ID { get; set; }
        public string Description { get; set; }
        public decimal Primo { get; set; }
        public decimal Period { get; set; }
        public decimal YTD { get; set; }
        public string Employee_No_ { get; set; }
        public System.DateTime Balance_Date { get; set; }
    }
}
