//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Holiday_Days
    {
        public byte[] timestamp { get; set; }
        public int Journal_Template { get; set; }
        public string Employee_No_ { get; set; }
        public int Holiday_Accumulation_Year { get; set; }
        public string Name { get; set; }
        public decimal Days { get; set; }
        public decimal Hours { get; set; }
        public decimal Net_Holiday_Pay { get; set; }
        public decimal Holiday_Bonus { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public string Pay_Type_No_ { get; set; }
        public byte Approved { get; set; }
        public byte Convertion { get; set; }
        public int Pay_Frequency { get; set; }
        public string Cause_of_Absene_Code { get; set; }
        public System.DateTime Seniority_Date_Add__Holiday { get; set; }
    }
}
