//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Lessor_Portal_Setup
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public string Account_ID { get; set; }
        public string Company_ID { get; set; }
        public string Portal_ID { get; set; }
        public string Request_Filename { get; set; }
        public string Response_Filename { get; set; }
        public string Lessor_Portal_URL { get; set; }
        public string Temp__Payslip_Storage_Location { get; set; }
        public string Lessor_Portal_Nos_ { get; set; }
        public string Temp__Storage_Location { get; set; }
        public byte Log_Synchronization { get; set; }
        public int XML_Viewer { get; set; }
        public string Payslip_Description { get; set; }
        public int Field_1_Replacement { get; set; }
        public int Field_2_Replacement { get; set; }
        public int Field_3_Replacement { get; set; }
        public int Field_4_Replacement { get; set; }
        public int Field_5_Replacement { get; set; }
        public System.DateTime Starting_transfer_of_payslips { get; set; }
        public byte Company_Created { get; set; }
        public byte Print_Pay_Slips { get; set; }
        public int Lessor_Portal_Absence_Year { get; set; }
        public string NemRefusion_Absence_Nos_ { get; set; }
        public string NemRefusion_Pay_Type_No_ { get; set; }
        public string NemRefusion_Journal_Name { get; set; }
    }
}
