//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_BA_Db__Cube_Measure
    {
        public byte[] timestamp { get; set; }
        public string BA_Db__Code { get; set; }
        public int BA_Db__Cube_Line_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Name { get; set; }
        public int Table_No_ { get; set; }
        public int Field_No_ { get; set; }
        public int Aggregation { get; set; }
        public string Expression { get; set; }
        public string Display_Format { get; set; }
    }
}
