//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Production_Document_Dimension
    {
        public byte[] timestamp { get; set; }
        public int Table_ID { get; set; }
        public int Document_Status { get; set; }
        public string Document_No_ { get; set; }
        public int Document_Line_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Dimension_Code { get; set; }
        public string Dimension_Value_Code { get; set; }
    }
}
