//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Employee_Qualification
    {
        public byte[] timestamp { get; set; }
        public string Employee_No_ { get; set; }
        public int Status { get; set; }
        public int Line_No_ { get; set; }
        public string Qualification_Code { get; set; }
        public System.DateTime From_Date { get; set; }
        public System.DateTime To_Date { get; set; }
        public int Type { get; set; }
        public string Description { get; set; }
        public string Institution_Company { get; set; }
        public decimal Cost { get; set; }
        public string Course_Grade { get; set; }
        public int Employee_Status { get; set; }
        public System.DateTime Expiration_Date { get; set; }
        public string DA_Qualification_Code { get; set; }
        public byte Transfer { get; set; }
        public string Employee_Name { get; set; }
        public int Week { get; set; }
        public int Quarter { get; set; }
        public int Year { get; set; }
    }
}
