//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_EP_Trusted_Site
    {
        public byte[] timestamp { get; set; }
        public int Entry_ID { get; set; }
        public string Site_Name { get; set; }
        public string Site_Address { get; set; }
        public System.DateTime Request_Date { get; set; }
        public System.DateTime Request_Time { get; set; }
        public byte[] Partner_Public_Key { get; set; }
        public string Req__Message_GUID { get; set; }
        public string Site_Identifier { get; set; }
        public byte Site_Trust { get; set; }
        public System.DateTime Trust_Date { get; set; }
        public System.DateTime Trust_Time { get; set; }
        public byte Answer_Sent { get; set; }
        public System.DateTime Sent_Date { get; set; }
        public System.DateTime Sent_Time { get; set; }
    }
}
