//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Add__Holiday_Acc__Period
    {
        public byte[] timestamp { get; set; }
        public int Accumulation_Year { get; set; }
        public string Add__Holiday_Code { get; set; }
        public System.DateTime Add__Holiday_Starting_Date { get; set; }
        public System.DateTime Liquidation_Starting_Date { get; set; }
        public System.DateTime Liquidation_Ending_Date { get; set; }
        public System.DateTime Accumulation_Starting_Date { get; set; }
        public System.DateTime Accumulation_Ending_Date { get; set; }
    }
}
