//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_HR_Attachment
    {
        public byte[] timestamp { get; set; }
        public int No_ { get; set; }
        public byte[] Attachment { get; set; }
        public int Storage_Type { get; set; }
        public string Storage_Pointer { get; set; }
        public string File_Extension { get; set; }
        public byte Read_Only { get; set; }
        public System.DateTime Last_Date_Modified { get; set; }
        public System.DateTime Last_Time_Modified { get; set; }
        public byte[] Store_Pointer_ID { get; set; }
        public int Store_Pointer_Checksum { get; set; }
        public byte[] Entry_Pointer_ID { get; set; }
        public int Entry_Pointer_Checksum { get; set; }
    }
}
