//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Outbound_Product_Catalog_Line
    {
        public byte[] timestamp { get; set; }
        public int Outbound_Document_No_ { get; set; }
        public string No_ { get; set; }
        public string No__2 { get; set; }
        public string Description { get; set; }
        public string Search_Description { get; set; }
        public string Description_2 { get; set; }
        public string Class { get; set; }
        public string Base_Unit_of_Measure { get; set; }
        public string Shelf_No_ { get; set; }
        public int Statistics_Group { get; set; }
        public int Commission_Group { get; set; }
        public decimal Unit_Price { get; set; }
        public int Costing_Method { get; set; }
        public decimal Unit_Cost { get; set; }
        public decimal Standard_Cost { get; set; }
        public decimal Last_Direct_Cost { get; set; }
        public decimal Average_Cost { get; set; }
        public string Vendor_No_ { get; set; }
        public string Vendor_Item_No_ { get; set; }
        public string Lead_Time_Calculation { get; set; }
        public decimal Reorder_Point { get; set; }
        public decimal Maximum_Inventory { get; set; }
        public decimal Reorder_Quantity { get; set; }
        public string Alternative_Item_No_ { get; set; }
        public decimal Unit_List_Price { get; set; }
        public string Duty_Code { get; set; }
        public decimal Gross_Weight { get; set; }
        public decimal Net_Weight { get; set; }
        public decimal Units_per_Parcel { get; set; }
        public decimal Unit_Volume { get; set; }
        public string Freight_Type { get; set; }
        public string Tariff_No_ { get; set; }
        public string Country_Purchased_Code { get; set; }
        public System.DateTime Date_Filter { get; set; }
        public string Department_Filter { get; set; }
        public string Project_Filter { get; set; }
        public string Location_Filter { get; set; }
        public decimal Inventory { get; set; }
        public decimal Net_Invoiced_Qty_ { get; set; }
        public decimal Purchases__Qty__ { get; set; }
        public decimal Sales__Qty__ { get; set; }
        public decimal Purchases__LCY_ { get; set; }
        public decimal Sales__LCY_ { get; set; }
        public decimal Qty__on_Purch__Order { get; set; }
        public decimal Qty__on_Sales_Order { get; set; }
        public byte Price_Includes_VAT { get; set; }
        public byte[] Picture { get; set; }
        public string Country_of_Origin_Code { get; set; }
        public int Low_Level_Code { get; set; }
        public decimal Lot_Size { get; set; }
        public int Discrete_Order_Quantity { get; set; }
        public decimal Minimum_Order_Quantity { get; set; }
        public decimal Maximum_Order_Quantity { get; set; }
        public string Safety_Lead_Time { get; set; }
        public string Bin_Filter { get; set; }
        public string Variant_Filter { get; set; }
        public string Sales_Unit_of_Measure { get; set; }
        public string Purch__Unit_of_Measure { get; set; }
        public string Common_Item_No_ { get; set; }
        public decimal Qty__per_Unit_of_Measure { get; set; }
    }
}
