//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Detailed_Cust__Ledg__Entry_VSIFT_7
    {
        public int Initial_Document_Type { get; set; }
        public string Customer_No_ { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public string Currency_Code { get; set; }
        public int Entry_Type { get; set; }
        public Nullable<long> C_Cnt { get; set; }
        public Nullable<decimal> SUM_Amount { get; set; }
        public Nullable<decimal> SUM_Amount__LCY_ { get; set; }
    }
}
