//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_HR_Human_Resource_Filter_Setup
    {
        public byte[] timestamp { get; set; }
        public string User_ID { get; set; }
        public string Human_Resource_Filter_Code { get; set; }
        public byte Administrator { get; set; }
    }
}
