//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Payment_Ledger_Entry_History
    {
        public byte[] timestamp { get; set; }
        public string Jnl__Template_Name { get; set; }
        public string Jnl__Batch_Name { get; set; }
        public int Jnl__Line_No_ { get; set; }
        public int Payment_Ledger_Entry_No_ { get; set; }
        public int Line_No_ { get; set; }
        public int Recipient_Type { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Time_Logged { get; set; }
        public string Sender { get; set; }
        public string Recipient { get; set; }
        public int Sent_by { get; set; }
        public string User_ID { get; set; }
        public string Action { get; set; }
        public string Comment { get; set; }
        public int Old_Status { get; set; }
        public int New_Status { get; set; }
    }
}
