//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Mapping_Header
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public int Table_no_ { get; set; }
        public string File_name { get; set; }
        public int First_DataRow { get; set; }
        public byte ValidateInsertModify { get; set; }
        public int ImportOption { get; set; }
        public byte AllowDuplicates { get; set; }
        public string Mapping_Group { get; set; }
    }
}
