//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_BizTalk_Partner_Setup_Header
    {
        public byte[] timestamp { get; set; }
        public int BizTalk_Partner_No_ { get; set; }
        public int Partner_Type { get; set; }
        public byte Auto__Rqst__for_Sales_Quote { get; set; }
        public byte Auto__Purchase_Quote { get; set; }
        public int Purchase_Quote { get; set; }
        public int Purchase_Quote__Qty_ { get; set; }
        public int Quote_Combined_Amt_Cost_Disc_ { get; set; }
        public int Purch__Quote_Expd__Rcpt__Date { get; set; }
        public byte Auto__Sales_Order { get; set; }
        public byte Auto__Purch__Order_Cnfmn_ { get; set; }
        public int Purch__Order_Cnfmn___Qty_ { get; set; }
        public int Ord_Cnfmn_Combd_Amt_Cost_Disc_ { get; set; }
        public int Purch_Ord_Cnfmn__Expd_Rcpt_D { get; set; }
        public byte Auto__Purchase_Invoice { get; set; }
        public int Purchase_Invoice { get; set; }
        public int Inv__Combined_Amt_Cost_Disc_ { get; set; }
        public byte Auto_Purchase_Receipt { get; set; }
        public int Item_Import_Destination { get; set; }
        public byte Auto__Purchase_Credit_Memo { get; set; }
        public byte Auto__Product_Catalog { get; set; }
        public int Item_Import_Action { get; set; }
        public byte Import_Item_Picture { get; set; }
        public byte Export_Item_Picture { get; set; }
        public int BizTalk_Organization_ID { get; set; }
        public string Partner_No_ { get; set; }
        public string Partner_Name { get; set; }
        public string BizTalk_Organization_Name { get; set; }
        public byte Delete_Referenced_Sales_Quote { get; set; }
        public int Sales_Item_Number_Type { get; set; }
        public int Purchase_Item_Number_Type { get; set; }
        public int Product_Item_Number_Type { get; set; }
        public int Update_Purchase_Comments { get; set; }
        public string Def__Inv__Posting_Group { get; set; }
        public string Def__Gen__Prod__Posting_Group { get; set; }
        public string Def__VAT_Prod__Posting_Group { get; set; }
        public int Create_Company_as_an { get; set; }
        public string BizTalk_Application_Name { get; set; }
        public int BizTalk_Application_ID { get; set; }
        public string Destination_Address { get; set; }
        public byte Use_Company_ID { get; set; }
    }
}
