//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_BOM_Ledger_Entry
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public int Reference_Type { get; set; }
        public int Reference_Entry_No_ { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public int Entry_Type { get; set; }
        public System.DateTime Document_Date { get; set; }
    }
}
