//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_HR_Appearance
    {
        public byte[] timestamp { get; set; }
        public string Appearance_Name { get; set; }
        public int Code { get; set; }
        public string Description { get; set; }
        public string Colour_Code { get; set; }
        public byte Bold { get; set; }
    }
}
