//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Prod__Order_Line_VSIFT_10
    {
        public string Item_No_ { get; set; }
        public string Variant_Code { get; set; }
        public string Location_Code { get; set; }
        public int Status { get; set; }
        public System.DateTime Due_Date { get; set; }
        public Nullable<long> C_Cnt { get; set; }
        public Nullable<decimal> SUM_Remaining_Qty___Base_ { get; set; }
    }
}
