//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Payroll_Translation
    {
        public byte[] timestamp { get; set; }
        public string Table_Name { get; set; }
        public int Table_ID { get; set; }
        public int Field_ID { get; set; }
        public string Code { get; set; }
        public int Language_ID { get; set; }
        public string Field_Name { get; set; }
        public string Description { get; set; }
        public string Language_Name { get; set; }
    }
}
