//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Synchronization_Picture_Queue
    {
        public byte[] timestamp { get; set; }
        public int No_ { get; set; }
        public string Target_Filename { get; set; }
        public byte[] Picture { get; set; }
        public int Command { get; set; }
    }
}
