//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Implementation_Status
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public int ImportIndustryMappingSys { get; set; }
        public int ImportIndustryMappingStatus { get; set; }
        public string ImportIndustryMappingPath { get; set; }
        public int ImportIndustrySetupSys { get; set; }
        public int ImportIndustrySetupStatus { get; set; }
        public string ImportIndustrySetupPath { get; set; }
        public int ImportQuestSetupSys { get; set; }
        public int ImportQuestSetupStatus { get; set; }
        public string ImportQuestSetupPath { get; set; }
        public int ExportMasterTablesSys { get; set; }
        public int ExportMasterTablesStatus { get; set; }
        public string ExportMasterCustomerPath { get; set; }
        public string ExportMasterVendorPath { get; set; }
        public string ExportMasterItemPath { get; set; }
        public string ExportMasterGLAccountPath { get; set; }
        public string ExportMasterContactPath { get; set; }
        public int ImportMasterTablesSys { get; set; }
        public int ImportMasterTablesStatus { get; set; }
        public string ImportMasterCustomerPath { get; set; }
        public string ImportMasterVendorPath { get; set; }
        public string ImportMasterItemPath { get; set; }
        public string ImportMasterGLAccountPath { get; set; }
        public string ImportMasterContactPath { get; set; }
        public int ValidateDataSys { get; set; }
        public int ValidateDataStatus { get; set; }
        public int DataCleaningSys { get; set; }
        public int DataCleaningStatus { get; set; }
        public int MasterDataExportStatus { get; set; }
        public string MasterDataExportWorkBookPath { get; set; }
        public int MasterDataImportStatus { get; set; }
        public string MasterDataImportWorkBookPath { get; set; }
    }
}
