//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Employment_Period
    {
        public byte[] timestamp { get; set; }
        public string Employee_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Name { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public System.DateTime Ending_Date { get; set; }
        public System.DateTime Last_Date_Modified { get; set; }
        public string User_ID { get; set; }
        public decimal Days { get; set; }
        public decimal Hours { get; set; }
        public string Description { get; set; }
        public string Cause_of_Inactivity_Code { get; set; }
        public byte Included_in_Holiday_Calc_ { get; set; }
        public byte Inactive { get; set; }
    }
}
