//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Invoice_Journal___Approved_VSIFT_1
    {
        public string Customer { get; set; }
        public string Course_No_ { get; set; }
        public string PO_No_ { get; set; }
        public string EAN_No_ { get; set; }
        public Nullable<long> C_Cnt { get; set; }
        public Nullable<decimal> SUM_Line_Amount { get; set; }
    }
}
