//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_PDF_Source_Setup
    {
        public byte[] timestamp { get; set; }
        public int Source_Type { get; set; }
        public string Source_No_ { get; set; }
        public int Entry_No_ { get; set; }
        public string Email { get; set; }
        public int Type { get; set; }
        public byte Active { get; set; }
        public byte Create { get; set; }
        public string Receiver_Code { get; set; }
    }
}
