//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Purch__Payment_Advice
    {
        public byte[] timestamp { get; set; }
        public string Jnl__Template_Name { get; set; }
        public string Jnl__Batch_Name { get; set; }
        public int Jnl__Line_No_ { get; set; }
        public int Document_Type { get; set; }
        public string Document_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Text { get; set; }
    }
}
