//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Bank_Account_No_
    {
        public byte[] timestamp { get; set; }
        public string Employee_No_ { get; set; }
        public string Pay_Type_No_ { get; set; }
        public string Description { get; set; }
        public string Bank_Branch_No_ { get; set; }
        public string Bank_Account_No_ { get; set; }
        public string Nets_No_ { get; set; }
        public string Insurance_Policy_No_ { get; set; }
        public string Currency_Code { get; set; }
        public string Country_Code { get; set; }
        public string IBAN { get; set; }
        public string SWIFT_Code { get; set; }
    }
}
