//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Entry_Summary
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public int Table_ID { get; set; }
        public string Summary_Type { get; set; }
        public decimal Total_Quantity { get; set; }
        public decimal Total_Reserved_Quantity { get; set; }
        public decimal Total_Available_Quantity { get; set; }
        public decimal Current_Reserved_Quantity { get; set; }
        public int Source_Subtype { get; set; }
        public decimal Qty__Alloc__in_Warehouse { get; set; }
        public string Serial_No_ { get; set; }
        public string Lot_No_ { get; set; }
        public System.DateTime Warranty_Date { get; set; }
        public System.DateTime Expiration_Date { get; set; }
        public decimal Total_Requested_Quantity { get; set; }
    }
}
