//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Cust__Account_Statement
    {
        public byte[] timestamp { get; set; }
        public string Number { get; set; }
        public string Customer_No_ { get; set; }
        public int Account_Statement_Entry_No_ { get; set; }
        public System.DateTime Date { get; set; }
        public string Number_Series { get; set; }
    }
}
