//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Payment_Ledger_Entry_Statistic
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public string Payment_Method { get; set; }
        public int No__of_Payments { get; set; }
        public int No__of_Collected_Payments { get; set; }
        public decimal Amount__LCY_ { get; set; }
        public decimal Fee__LCY_ { get; set; }
        public string Description { get; set; }
    }
}
