//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDF_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Å99___dlu_Pay_Type
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public string Description { get; set; }
        public System.DateTime Last_Date_Modified { get; set; }
        public decimal Factor { get; set; }
        public int Pay_Slip { get; set; }
        public string Yearly_Tax_Statement { get; set; }
        public string Field_68_Code { get; set; }
        public int Bank_Transfer_Receiver { get; set; }
        public int Bank_Transfer_Type { get; set; }
        public string Input_Units { get; set; }
        public string Input_Rate { get; set; }
        public byte Create_automatically { get; set; }
        public decimal Reg__Journal_Units { get; set; }
        public decimal Reg__Journal_Amount { get; set; }
        public string Search_Name { get; set; }
        public string IL_Codes_Number { get; set; }
        public string IL_Codes_Amount { get; set; }
        public byte Blocked { get; set; }
        public string Rounding_Method { get; set; }
        public string Work_Type_Code { get; set; }
        public byte Include_if_Input { get; set; }
        public int Calculation_Function { get; set; }
        public int Rate_Search_Method { get; set; }
        public int Pay_Slip_Column { get; set; }
        public string Input_Amount { get; set; }
        public int Type { get; set; }
        public byte Allocation_Ratio { get; set; }
        public byte Don_t_show_zeroline { get; set; }
        public byte Don_t_show_Units { get; set; }
        public byte Don_t_show_Rate { get; set; }
        public byte Don_t_show_Amount { get; set; }
        public int Sorting { get; set; }
        public string Maternity_Arrangement { get; set; }
        public byte eIndkomst_Reverse_Sign { get; set; }
        public string eIndkomst_Type_Amount { get; set; }
        public string eIndkomst_Type_Units { get; set; }
        public string Income_Type_Code_68 { get; set; }
        public byte Regulate_Salary_per_Date { get; set; }
        public byte Holiday_Pay_Term__Sal__Earner { get; set; }
        public byte Show_Holiday_Accumulation { get; set; }
    }
}
