//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreatetblLaesertaleleTilWeb
    {
        public int BladId { get; set; }
        public Nullable<int> Antal_13 { get; set; }
        public Nullable<byte> Antal_13_ { get; set; }
        public string primaerkommuner { get; set; }
        public Nullable<int> modtager_pri { get; set; }
        public Nullable<int> laesedaekning_pri { get; set; }
    }
}
