//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreateModtagelseseleTilWeb
    {
        public int BladId { get; set; }
        public string ads_nummer { get; set; }
        public Nullable<int> ads_kanaler { get; set; }
        public string isdn_nummer { get; set; }
        public Nullable<int> isdn_kanaler { get; set; }
        public string easynummer { get; set; }
        public Nullable<byte> easy_kanaler { get; set; }
    }
}
