//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class mmprAnnoncørprUge
    {
        public int OrdreNr { get; set; }
        public Nullable<short> mm { get; set; }
        public string Annoncør { get; set; }
    }
}
