//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class NulltblBlade
    {
        public int BladId { get; set; }
        public string GeoKode { get; set; }
        public Nullable<short> KortNr { get; set; }
        public string DelOmr { get; set; }
        public string Navn { get; set; }
        public string Adresse { get; set; }
        public string PostNr { get; set; }
        public string Tlf { get; set; }
        public string Fax { get; set; }
        public Nullable<int> Oplag { get; set; }
        public string UgeDag { get; set; }
        public Nullable<decimal> mmPris { get; set; }
        public Nullable<byte> Rabat { get; set; }
        public Nullable<int> Antal_13 { get; set; }
        public Nullable<byte> Antal_13_ { get; set; }
        public string RegText { get; set; }
        public Nullable<bool> DeAktiveret { get; set; }
        public string Email { get; set; }
        public Nullable<bool> DelMail { get; set; }
    }
}
