//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class OmsætningssammenligningPrBladRegnskabsår
    {
        public string Navn { get; set; }
        public Nullable<double> Oms2004 { get; set; }
        public Nullable<double> Oms2005 { get; set; }
        public string GeoKode { get; set; }
        public string DD_DL { get; set; }
        public Nullable<int> Oplag { get; set; }
    }
}
