//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class OmsætningPrAntalBladePrGeokode
    {
        public Nullable<int> AntalIalt { get; set; }
        public Nullable<int> AntalIAlt2 { get; set; }
        public Nullable<decimal> BruttoIAlt { get; set; }
        public Nullable<double> NettoIAlt { get; set; }
        public string ialtsep { get; set; }
        public Nullable<int> HTAntal { get; set; }
        public Nullable<decimal> HTBrutto { get; set; }
        public Nullable<double> HTNetto { get; set; }
        public string htsep { get; set; }
        public Nullable<int> SjælAntal { get; set; }
        public Nullable<decimal> SjælBrutto { get; set; }
        public Nullable<double> SjælNetto { get; set; }
        public string sjælsep { get; set; }
        public Nullable<int> FynAntal { get; set; }
        public Nullable<decimal> FynBrutto { get; set; }
        public Nullable<double> FynNetto { get; set; }
        public string fynsep { get; set; }
        public Nullable<int> JylAntal { get; set; }
        public Nullable<decimal> JylBrutto { get; set; }
        public Nullable<double> JylNetto { get; set; }
    }
}
