//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class OmsætningAnnoncører
    {
        public string Annoncør { get; set; }
        public Nullable<int> AntalOrdre { get; set; }
        public Nullable<int> AntalAnnoncer { get; set; }
        public Nullable<int> htAntal { get; set; }
        public Nullable<decimal> htPris { get; set; }
        public string sep1 { get; set; }
        public Nullable<double> htRabatPris { get; set; }
        public Nullable<decimal> htFarvePris { get; set; }
        public string sep2 { get; set; }
        public Nullable<double> htFarveRabatPris { get; set; }
        public string sep3 { get; set; }
        public string sep4 { get; set; }
        public string sep5 { get; set; }
        public Nullable<int> sjælAntal { get; set; }
        public Nullable<decimal> sjælPris { get; set; }
        public string sep6 { get; set; }
        public Nullable<double> sjælRabatPris { get; set; }
        public Nullable<decimal> sjælFarvePris { get; set; }
        public string sep7 { get; set; }
        public Nullable<double> sjælFarveRabatPris { get; set; }
        public string sep8 { get; set; }
        public string sep9 { get; set; }
        public string sep10 { get; set; }
        public Nullable<int> fynAntal { get; set; }
        public Nullable<decimal> fynPris { get; set; }
        public string sep11 { get; set; }
        public Nullable<double> fynRabatPris { get; set; }
        public Nullable<decimal> fynFarvePris { get; set; }
        public string sep12 { get; set; }
        public Nullable<double> fynFarveRabatPris { get; set; }
        public string sep13 { get; set; }
        public string sep14 { get; set; }
        public string sep15 { get; set; }
        public Nullable<int> jylAntal { get; set; }
        public Nullable<decimal> jylPris { get; set; }
        public string sep16 { get; set; }
        public Nullable<double> jylRabatPris { get; set; }
        public Nullable<decimal> jylFarvePris { get; set; }
        public string sep17 { get; set; }
        public Nullable<double> jylFarveRabatPris { get; set; }
    }
}
