//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class prisele
    {
        public int hovedid { get; set; }
        public Nullable<decimal> tekstside { get; set; }
        public Nullable<decimal> side3 { get; set; }
        public Nullable<decimal> side5 { get; set; }
        public Nullable<decimal> side7 { get; set; }
        public Nullable<decimal> hojreside { get; set; }
        public Nullable<decimal> specialside { get; set; }
        public Nullable<decimal> forlystelser { get; set; }
        public Nullable<decimal> stillinger { get; set; }
        public Nullable<decimal> officielle { get; set; }
        public Nullable<decimal> rubrik { get; set; }
        public Nullable<decimal> farvetillaeg { get; set; }
        public Nullable<decimal> firefarvetillaeg { get; set; }
        public Nullable<decimal> mm_hovedblad { get; set; }
        public Nullable<decimal> mm_suppblad { get; set; }
    }
}
