//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class SøgIJuleliste
    {
        public int ID { get; set; }
        public string Navn { get; set; }
        public string Adresse { get; set; }
        public int PostNr { get; set; }
        public string PostBy { get; set; }
        public string Att { get; set; }
    }
}
