//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAnnoncemængder
    {
        public int AnnonceregID { get; set; }
        public Nullable<int> BladID { get; set; }
        public Nullable<short> År { get; set; }
        public Nullable<byte> Kvartal { get; set; }
        public Nullable<int> T1Kmm { get; set; }
        public Nullable<int> R1Kmm { get; set; }
        public Nullable<int> Ialt1Kmm { get; set; }
        public Nullable<int> T1Kkr { get; set; }
        public Nullable<int> R1Kkr { get; set; }
        public Nullable<int> Ialt1Kkr { get; set; }
        public Nullable<byte> BladTR { get; set; }
        public Nullable<double> BladTotal { get; set; }
        public string Bemærkning { get; set; }
    }
}
