//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBladUdsendingKontakter
    {
        public int id { get; set; }
        public Nullable<int> bladid { get; set; }
        public string navn { get; set; }
        public string mail { get; set; }
        public Nullable<int> telefonnummer { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> titel { get; set; }
    }
}
