//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBladGrupper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBladGrupper()
        {
            this.tblBladeOLDs = new HashSet<tblBladeOLD>();
        }
    
        public byte GruppeID { get; set; }
        public int GruppeHovedbladID { get; set; }
        public string GruppeNavn { get; set; }
        public Nullable<bool> MaterialeGodtAlle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBladeOLD> tblBladeOLDs { get; set; }
        public virtual tblBladeOLD tblBladeOLD { get; set; }
    }
}
