//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBladStamDatabackup
    {
        public int BladID { get; set; }
        public string Navn { get; set; }
        public string Navn2 { get; set; }
        public string Adresse { get; set; }
        public string Adresse2 { get; set; }
        public Nullable<int> PostNr { get; set; }
        public string Tlf { get; set; }
        public string Fax { get; set; }
        public string CVR { get; set; }
        public string FIK { get; set; }
        public string Kontaktperson { get; set; }
        public Nullable<byte> HovedgruppeID { get; set; }
        public Nullable<byte> MedlemMåned { get; set; }
        public Nullable<byte> MedlemÅr { get; set; }
        public Nullable<System.DateTime> MedlemSiden { get; set; }
        public string Ejerforhold { get; set; }
        public bool Ophørt { get; set; }
        public bool VisPåWWW { get; set; }
        public Nullable<byte> RegionID { get; set; }
        public Nullable<byte> DelOmrådeID { get; set; }
        public string DiMPDelOmrådeKode { get; set; }
        public Nullable<byte> GeoKodeID { get; set; }
        public Nullable<int> Totalområde { get; set; }
        public Nullable<byte> TotalområdePct { get; set; }
        public Nullable<int> Primær { get; set; }
        public Nullable<byte> PrimærPct { get; set; }
        public string WWWDækningSomTekst { get; set; }
        public Nullable<int> Oplag { get; set; }
        public Nullable<byte> UgedagID { get; set; }
        public string Format { get; set; }
        public string OrdredeadlineTekst { get; set; }
        public string OrdredeadlineRubrik { get; set; }
        public string MaterialedeadlineTekst { get; set; }
        public string MaterialedeadlineRubrik { get; set; }
        public string OrdreEmail { get; set; }
        public string OrdrecheckEmail { get; set; }
        public Nullable<byte> OrdrecheckSendeDagID { get; set; }
        public string SendetidOrdrecheck { get; set; }
        public Nullable<bool> SendIndeværendeUge { get; set; }
        public string StamdataEmail { get; set; }
        public string PrisforespørgselEmails { get; set; }
        public string OrienteringEmails { get; set; }
        public string Emails { get; set; }
        public string KontaktpersonerEmails { get; set; }
        public string BogholderiEmails { get; set; }
        public string BogholderiKontaktperson { get; set; }
        public string MedieNetKode { get; set; }
        public Nullable<byte> MatGodtBeløb { get; set; }
        public string Hjemmeside { get; set; }
        public string RedaktionEmail { get; set; }
        public string AnnonceEmail { get; set; }
        public string MaterialeEmail { get; set; }
        public string AnnonceKontrolEmail { get; set; }
        public string BilagsbladeEmail { get; set; }
        public int FakturaGruppeID { get; set; }
        public Nullable<int> SalgsGruppeID { get; set; }
        public string GruppeRabat { get; set; }
        public string SamannonceringsRabat { get; set; }
        public Nullable<bool> MåGiveFarveRabat { get; set; }
        public bool GiverWebTillæg { get; set; }
        public bool Overført { get; set; }
        public byte[] timestamp { get; set; }
    }
}
