//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEjerforhold
    {
        public int EjerforholdID { get; set; }
        public string Ejerforhold { get; set; }
        public decimal WebTillægTekst { get; set; }
        public decimal WebTillægRubrik { get; set; }
    }
}
