//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGruppeRabatter
    {
        public int RabatFormID { get; set; }
        public int GruppeID { get; set; }
        public byte PlaceringID { get; set; }
        public byte AntalFra { get; set; }
        public byte AntalTil { get; set; }
        public Nullable<float> MmRabat { get; set; }
        public Nullable<float> FarveRabat { get; set; }
        public Nullable<decimal> MmPris { get; set; }
        public Nullable<decimal> FarveMin { get; set; }
        public Nullable<decimal> FarveMax { get; set; }
        public Nullable<decimal> FarveTillæg { get; set; }
        public Nullable<decimal> PrisInclFarver { get; set; }
        public byte Version { get; set; }
    }
}
