//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGrupper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGrupper()
        {
            this.tblMedIGruppes = new HashSet<tblMedIGruppe>();
        }
    
        public int GruppeID { get; set; }
        public string GruppeNavn { get; set; }
        public string GruppeType { get; set; }
        public byte AntalBladeForValg { get; set; }
        public Nullable<int> GruppeHovedbladID { get; set; }
        public string OrdreEmail { get; set; }
        public string MaterialeModtager { get; set; }
        public byte Version { get; set; }
        public byte[] timestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMedIGruppe> tblMedIGruppes { get; set; }
    }
}
