//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKontakterPrBlad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKontakterPrBlad()
        {
            this.tblKontaktFunktioners = new HashSet<tblKontaktFunktioner>();
        }
    
        public int BladID { get; set; }
        public int KontaktID { get; set; }
    
        public virtual tblBladStamdataKopi tblBladStamdataKopi { get; set; }
        public virtual tblKontakter tblKontakter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKontaktFunktioner> tblKontaktFunktioners { get; set; }
    }
}
