//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKonkurrentDækning
    {
        public byte KonkurrentID { get; set; }
        public int PostNr { get; set; }
        public int Oplag { get; set; }
        public int DækningsGrad { get; set; }
    
        public virtual tblKonkurrenter tblKonkurrenter { get; set; }
        public virtual tblPostNr tblPostNr { get; set; }
    }
}
