//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMedIGruppe
    {
        public int GruppeID { get; set; }
        public int ID { get; set; }
        public bool ErTillægsAvis { get; set; }
        public byte Version { get; set; }
    
        public virtual tblBladStamdata tblBladStamdata { get; set; }
        public virtual tblGrupper tblGrupper { get; set; }
    }
}
