//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrdreLinjerSlettet
    {
        public int OrdreNr { get; set; }
        public int BladId { get; set; }
        public Nullable<decimal> AnvendtPris { get; set; }
        public Nullable<double> SpecialRabat { get; set; }
        public Nullable<decimal> FarveTillægsPris { get; set; }
        public Nullable<double> FarveTillægsRabat { get; set; }
        public Nullable<double> FarveTillægsType { get; set; }
        public Nullable<bool> SlutVist { get; set; }
        public Nullable<bool> SlutFaktureret { get; set; }
        public Nullable<bool> Fejl { get; set; }
        public Nullable<bool> MaterialeGodt { get; set; }
        public Nullable<decimal> TotalPris { get; set; }
        public Nullable<decimal> MaterialePris { get; set; }
        public Nullable<bool> ErKontrolleret { get; set; }
        public Nullable<byte> BladGruppeID { get; set; }
        public Nullable<byte> DataÆndret { get; set; }
        public string Bureauordrenr { get; set; }
        public string Materialenr { get; set; }
    
        public virtual tblBladeOLD tblBladeOLD { get; set; }
        public virtual tblOrdrer tblOrdrer { get; set; }
    }
}
