//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlannerPlaner
    {
        public int plannerID { get; set; }
        public int brugerID { get; set; }
        public string bureau { get; set; }
        public string format { get; set; }
        public byte farver { get; set; }
        public byte mmType { get; set; }
        public string blade { get; set; }
        public int DimpOrdreNr { get; set; }
        public Nullable<int> Konsulent { get; set; }
    
        public virtual tblMmTyper tblMmTyper { get; set; }
    }
}
