//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStillinger
    {
        public int StillingID { get; set; }
        public string Sælger { get; set; }
        public Nullable<int> HovedbladID { get; set; }
        public string Annoncør { get; set; }
        public string Job { get; set; }
        public Nullable<short> Aar { get; set; }
        public Nullable<byte> Uge { get; set; }
        public Nullable<short> Mm { get; set; }
        public Nullable<bool> Farvetillæg { get; set; }
        public Nullable<byte> AntalFarver { get; set; }
        public Nullable<System.DateTime> Oprettet { get; set; }
    }
}
