//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUdsendteLister
    {
        public int År { get; set; }
        public byte Dag { get; set; }
        public byte Uge { get; set; }
        public byte AntalUdsendteLister { get; set; }
    }
}
