//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dimp_sql_services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tekniskele
    {
        public int hovedid { get; set; }
        public string kontaktper { get; set; }
        public string udgivesaf { get; set; }
        public string shb { get; set; }
        public string satssted { get; set; }
        public string tryksted { get; set; }
        public string ind_tekst { get; set; }
        public string ind_rubrik { get; set; }
    }
}
