//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlu_persistence_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class AktiveUgeaviserMedAlleData
    {
        public int BladID { get; set; }
        public string Navn { get; set; }
        public string Adresse { get; set; }
        public Nullable<int> PostNr { get; set; }
        public string PostBy { get; set; }
        public string Tlf { get; set; }
        public string Fax { get; set; }
        public string CVR { get; set; }
        public string Kontaktperson { get; set; }
        public string HovedGruppeNavn { get; set; }
        public Nullable<byte> MedlemMåned { get; set; }
        public Nullable<byte> MedlemÅr { get; set; }
        public string Ejerforhold { get; set; }
        public string RegionNavn { get; set; }
        public string DelOmrådeNavn { get; set; }
        public string DiMPDelOmrådeKode { get; set; }
        public string GeoKodeNavn { get; set; }
        public Nullable<int> Totalområde { get; set; }
        public Nullable<byte> TotalområdePct { get; set; }
        public Nullable<int> Primær { get; set; }
        public Nullable<byte> PrimærPct { get; set; }
        public string WWWDækningSomTekst { get; set; }
        public Nullable<int> Oplag { get; set; }
        public string Udgivelsesdag { get; set; }
        public string Format { get; set; }
        public string OrdredeadlineTekst { get; set; }
        public string OrdredeadlineRubrik { get; set; }
        public string MaterialedeadlineTekst { get; set; }
        public string MaterialedeadlineRubrik { get; set; }
        public string OrdreEmail { get; set; }
        public string OrdrecheckEmail { get; set; }
        public string OrdrecheckSendeDag { get; set; }
        public string SendetidOrdrecheck { get; set; }
        public Nullable<bool> SendIndeværendeUge { get; set; }
        public string StamdataEmail { get; set; }
        public string PrisforespørgselEmails { get; set; }
        public string OrienteringEmails { get; set; }
        public string Emails { get; set; }
        public string KontaktpersonerEmails { get; set; }
        public string BogholderiEmails { get; set; }
        public string BogholderiKontaktperson { get; set; }
        public string MedieNetKode { get; set; }
        public string Hjemmeside { get; set; }
        public string RedaktionEmail { get; set; }
        public string AnnonceEmail { get; set; }
        public string MaterialeEmail { get; set; }
        public string AnnonceKontrolEmail { get; set; }
        public string BilagsbladeEmail { get; set; }
        public string FakturaGruppe { get; set; }
        public string GruppeRabat { get; set; }
        public string SamannonceringsRabat { get; set; }
    }
}
