//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlu_persistence_api
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiMPdotNetEntities1 : DbContext
    {
        public DiMPdotNetEntities1()
            : base("name=DiMPdotNetEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<OpdateringsTekst> OpdateringsTeksts { get; set; }
        public virtual DbSet<StamBladKontaktPersoner> StamBladKontaktPersoners { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblAnnoncekontrol> tblAnnoncekontrols { get; set; }
        public virtual DbSet<tblBladDækning> tblBladDækning { get; set; }
        public virtual DbSet<tblBladnavnMappingFraDO> tblBladnavnMappingFraDOes { get; set; }
        public virtual DbSet<tblBladStamdata> tblBladStamdatas { get; set; }
        public virtual DbSet<tblBladStamdataKopi> tblBladStamdataKopis { get; set; }
        public virtual DbSet<tblBrugerData> tblBrugerDatas { get; set; }
        public virtual DbSet<tblDage> tblDages { get; set; }
        public virtual DbSet<tblDelOmråde> tblDelOmråde { get; set; }
        public virtual DbSet<tblDPKulør> tblDPKulør { get; set; }
        public virtual DbSet<tblEjerforhold> tblEjerforholds { get; set; }
        public virtual DbSet<tblFakturaFejl> tblFakturaFejls { get; set; }
        public virtual DbSet<tblFakturaFejlTekst> tblFakturaFejlTeksts { get; set; }
        public virtual DbSet<tblFaktureringsBilag> tblFaktureringsBilags { get; set; }
        public virtual DbSet<tblFejlTekst> tblFejlTeksts { get; set; }
        public virtual DbSet<tblGeoKode> tblGeoKodes { get; set; }
        public virtual DbSet<tblGrupper> tblGruppers { get; set; }
        public virtual DbSet<tblGruppeRabatter> tblGruppeRabatters { get; set; }
        public virtual DbSet<tblHovedGruppe> tblHovedGruppes { get; set; }
        public virtual DbSet<tblKonkurrentDækning> tblKonkurrentDækning { get; set; }
        public virtual DbSet<tblKonkurrenter> tblKonkurrenters { get; set; }
        public virtual DbSet<tblKontaktArbOmråder> tblKontaktArbOmråder { get; set; }
        public virtual DbSet<tblKontakter> tblKontakters { get; set; }
        public virtual DbSet<tblKontakterPrBlad> tblKontakterPrBlads { get; set; }
        public virtual DbSet<tblKontaktFunktioner> tblKontaktFunktioners { get; set; }
        public virtual DbSet<tblKontaktTitler> tblKontaktTitlers { get; set; }
        public virtual DbSet<tblMateriale> tblMateriales { get; set; }
        public virtual DbSet<tblMedieplan> tblMedieplans { get; set; }
        public virtual DbSet<tblMedieplanÆndringer> tblMedieplanÆndringer { get; set; }
        public virtual DbSet<tblMedieplanLinjer> tblMedieplanLinjers { get; set; }
        public virtual DbSet<tblMedieplanNr> tblMedieplanNrs { get; set; }
        public virtual DbSet<tblMedIGruppe> tblMedIGruppes { get; set; }
        public virtual DbSet<tblOrdreGebyrNavision> tblOrdreGebyrNavisions { get; set; }
        public virtual DbSet<tblOrdreLinjerNavision> tblOrdreLinjerNavisions { get; set; }
        public virtual DbSet<tblOrdreNavision> tblOrdreNavisions { get; set; }
        public virtual DbSet<tblPlacering> tblPlacerings { get; set; }
        public virtual DbSet<tblPostNr> tblPostNrs { get; set; }
        public virtual DbSet<tblPostNrSøgning> tblPostNrSøgning { get; set; }
        public virtual DbSet<tblPriser> tblPrisers { get; set; }
        public virtual DbSet<tblPrislister> tblPrislisters { get; set; }
        public virtual DbSet<tblPrislisterPrBladPrÅr> tblPrislisterPrBladPrÅr { get; set; }
        public virtual DbSet<tblPrislisterPrBladPrUge> tblPrislisterPrBladPrUges { get; set; }
        public virtual DbSet<tblRegion> tblRegions { get; set; }
        public virtual DbSet<tblRemindereSendt> tblRemindereSendts { get; set; }
        public virtual DbSet<tblSupportBilag> tblSupportBilags { get; set; }
        public virtual DbSet<tblWEBeMail> tblWEBeMails { get; set; }
        public virtual DbSet<tblWEBForespørgsel> tblWEBForespørgsel { get; set; }
        public virtual DbSet<tblWEBForespørgselLinjer> tblWEBForespørgselLinjer { get; set; }
        public virtual DbSet<tblWEBSendTilKollega> tblWEBSendTilKollegas { get; set; }
        public virtual DbSet<UserTable2> UserTable2 { get; set; }
        public virtual DbSet<bladtlfogfaxkopi> bladtlfogfaxkopis { get; set; }
        public virtual DbSet<delPriser> delPrisers { get; set; }
        public virtual DbSet<HerningFolkeblad> HerningFolkeblads { get; set; }
        public virtual DbSet<tblAktiveVærdier> tblAktiveVærdier { get; set; }
        public virtual DbSet<tblAktivGruppeVersion> tblAktivGruppeVersions { get; set; }
        public virtual DbSet<tblFarveTillægWebApp> tblFarveTillægWebApp { get; set; }
        public virtual DbSet<tblMmPrisWebApp> tblMmPrisWebApps { get; set; }
        public virtual DbSet<tblPlannerPlaner> tblPlannerPlaners { get; set; }
        public virtual DbSet<tempPriser> tempPrisers { get; set; }
        public virtual DbSet<tmpNyeDeadline> tmpNyeDeadlines { get; set; }
        public virtual DbSet<tnpOrdreNr> tnpOrdreNrs { get; set; }
        public virtual DbSet<tnpOrdreNr2> tnpOrdreNr2 { get; set; }
        public virtual DbSet<tnpOrdreNr3> tnpOrdreNr3 { get; set; }
    }
}
