//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlu_persistence_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salesperson
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string E_Mail { get; set; }
        public string Phone_No_ { get; set; }
        public int Status { get; set; }
        public string SidsteLoginVersion { get; set; }
        public Nullable<bool> NulstilLayout { get; set; }
        public string Rolle { get; set; }
    }
}
