//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlu_persistence_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public int askingID { get; set; }
        public int stambladId { get; set; }
        public string name { get; set; }
        public string telefon { get; set; }
        public string mail { get; set; }
    }
}
