//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlu_persistence_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAktiveVærdier
    {
        public byte GruppeVersion { get; set; }
        public decimal MiljøTillæg { get; set; }
        public byte PrisberegningVersion { get; set; }
        public byte BilagsBladeSendeUge { get; set; }
    }
}
