//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlu_persistence_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAnnoncekontrol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAnnoncekontrol()
        {
            this.tblMedieplanLinjers = new HashSet<tblMedieplanLinjer>();
        }
    
        public int MedieplanNr { get; set; }
        public int UgeavisID { get; set; }
        public bool ErKontrolleret { get; set; }
        public System.DateTime KontrolTidspunkt { get; set; }
        public string KontrollørEmail { get; set; }
        public bool KontrolleretAfDLU { get; set; }
        public byte Fejlkode { get; set; }
        public string Ansvar { get; set; }
        public string IndrykketPåSide { get; set; }
        public string FaktureresTil { get; set; }
        public byte SidePlacering { get; set; }
    
        public virtual tblFejlTekst tblFejlTekst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMedieplanLinjer> tblMedieplanLinjers { get; set; }
    }
}
 