//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlu_persistence_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFarveTillægWebApp
    {
        public int BladID { get; set; }
        public Nullable<decimal> farvePris { get; set; }
        public Nullable<short> farveMin { get; set; }
        public Nullable<short> farveMax { get; set; }
        public Nullable<decimal> farve4Pris { get; set; }
        public Nullable<short> farve4Min { get; set; }
        public Nullable<short> farve4Max { get; set; }
        public Nullable<bool> Godkendt { get; set; }
        public string PrisBemærkning { get; set; }
    }
}
