//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlu_persistence_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKontakter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKontakter()
        {
            this.tblKontakterPrBlads = new HashSet<tblKontakterPrBlad>();
            this.tblKontaktArbOmråder = new HashSet<tblKontaktArbOmråder>();
        }
    
        public int KontaktID { get; set; }
        public string Fornavn { get; set; }
        public string Efternavn { get; set; }
        public Nullable<int> TitelID { get; set; }
        public string Tlfnr { get; set; }
        public string Mobilnr { get; set; }
        public string Email { get; set; }
    
        public virtual tblKontaktTitler tblKontaktTitler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKontakterPrBlad> tblKontakterPrBlads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKontaktArbOmråder> tblKontaktArbOmråder { get; set; }
    }
}
