//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlu_persistence_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMedieplanNr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMedieplanNr()
        {
            this.tblMateriales = new HashSet<tblMateriale>();
            this.tblMedieplans = new HashSet<tblMedieplan>();
        }
    
        public int MedieplanNr { get; set; }
        public short AktivVersion { get; set; }
        public byte Status { get; set; }
        public bool SupportBilagVedlagt { get; set; }
        public bool SupportBilagVist { get; set; }
        public string FakturaBemærkning1 { get; set; }
        public string FakturaBemærkning2 { get; set; }
        public string FakturaBemærkning3 { get; set; }
        public bool MaterialeModtaget { get; set; }
        public byte BrugtGruppeVersion { get; set; }
        public bool OverførtFraPrisforespørgsel { get; set; }
        public decimal AnvendtMiljøTillæg { get; set; }
        public byte AnvendtPrisberegningVersion { get; set; }
        public string Kommentar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMateriale> tblMateriales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMedieplan> tblMedieplans { get; set; }
    }
}
