//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlu_persistence_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrdreGebyrNavision
    {
        public int OrdreNr { get; set; }
        public short Version { get; set; }
        public byte Document_Type { get; set; }
        public byte Type { get; set; }
        public int BladId { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
    
        public virtual tblOrdreNavision tblOrdreNavision { get; set; }
    }
}
