//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlu_persistence_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPriser
    {
        public int BladID { get; set; }
        public byte PlaceringID { get; set; }
        public short År { get; set; }
        public int PrislisteID { get; set; }
        public int FormatFra { get; set; }
        public int FormatTil { get; set; }
        public Nullable<decimal> mmPris { get; set; }
        public Nullable<decimal> FarvePris { get; set; }
        public Nullable<decimal> FarveMin { get; set; }
        public Nullable<decimal> FarveMax { get; set; }
        public Nullable<decimal> Farve4Pris { get; set; }
        public Nullable<decimal> Farve4Min { get; set; }
        public Nullable<decimal> Farve4Max { get; set; }
        public string ControlNavn { get; set; }
    
        public virtual tblBladStamdata tblBladStamdata { get; set; }
        public virtual tblPlacering tblPlacering { get; set; }
        public virtual tblPrislister tblPrislister { get; set; }
    }
}
