//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlu_persistence_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupportBilag
    {
        public int MedieplanNr { get; set; }
        public string IndrykningsUge { get; set; }
        public byte MaterialeGodtgørelseTil { get; set; }
        public byte MaterialeFølgerFra { get; set; }
        public string MaterialeFølgerFraLeverandør { get; set; }
        public string BrugMaterialeFraUge { get; set; }
        public bool SammeMateriale { get; set; }
        public bool KunForhandlerBundForskellig { get; set; }
        public byte Fakturering { get; set; }
        public byte BureauOrdresedlerLiggerIIndbakke { get; set; }
        public byte Bilagsblade { get; set; }
        public string BilagsbladeAtt { get; set; }
        public string LøbendeOrdre { get; set; }
        public string BemærkningTilBlade { get; set; }
        public string BemærkningTilSupport { get; set; }
        public string Overskrift { get; set; }
        public short BilagsBladeTil { get; set; }
        public string BilagsBladeTilNavn { get; set; }
        public string BilagsBladeTilAdresse { get; set; }
        public int BilagsBladeTilPostNr { get; set; }
    }
}
