//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlu_persistence_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpNyeDeadline
    {
        public int BladID { get; set; }
        public short Linje { get; set; }
        public byte OrdreDeadline { get; set; }
        public string OrdreTid { get; set; }
        public byte MaterialeDeadline { get; set; }
        public string MaterialeTid { get; set; }
    }
}
