//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlu_persistence_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class UgeaviserTilGrid
    {
        public int BladID { get; set; }
        public string Navn { get; set; }
        public Nullable<int> PostNr { get; set; }
        public string PostBy { get; set; }
        public Nullable<int> Oplag { get; set; }
        public Nullable<int> DækningsGrad { get; set; }
        public string RegionNavn { get; set; }
        public byte RegionSortKey { get; set; }
        public string GeoKodeNavn { get; set; }
        public byte GeoKodeSortKey { get; set; }
        public string HovedGruppeNavn { get; set; }
        public byte HovedGruppeSortKey { get; set; }
        public string DelOmrådeNavn { get; set; }
        public byte DelOmrådeSortKey { get; set; }
        public string DagNavn { get; set; }
        public string GruppeNavn { get; set; }
        public string Navn2 { get; set; }
        public string Adresse { get; set; }
        public string Adresse2 { get; set; }
        public string Tlf { get; set; }
        public string Fax { get; set; }
        public string CVR { get; set; }
        public string Kontaktperson { get; set; }
        public string OrdredeadlineTekst { get; set; }
        public string OrdredeadlineRubrik { get; set; }
        public string MaterialedeadlineTekst { get; set; }
        public string MaterialedeadlineRubrik { get; set; }
    }
}
