//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlu_persistence_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewOrdre
    {
        public int OrdreNr { get; set; }
        public short Version { get; set; }
        public byte Document_Type { get; set; }
        public string AnnoncørID { get; set; }
        public byte Uge { get; set; }
        public byte AntalFarver { get; set; }
        public System.DateTime OrdreDato { get; set; }
        public decimal SamletPris { get; set; }
        public string SælgerKode { get; set; }
        public bool SikkerhedsGodt { get; set; }
        public bool InfoGodt { get; set; }
        public string BureauOrdreNr { get; set; }
        public string Bureau { get; set; }
        public byte EnOrdre { get; set; }
        public byte Status { get; set; }
        public string FakBem1 { get; set; }
        public string FakBem2 { get; set; }
        public string FakBem3 { get; set; }
        public byte MaterialeGodtgørelseTil { get; set; }
        public int Previous_Order_No { get; set; }
        public string Credit_Reason { get; set; }
        public Nullable<int> Previous_Version { get; set; }
        public string Item_Description { get; set; }
    }
}
